### ISSUE TITLE
Native build fails on OSX when libintl is present

### ISSUE THREAD

**Issue by dagood** [dotnet/coreclr#20092]
Building on a Mac with `libintl` installed causes the build to fail:

```
-- Looking for include file libintl.h
-- Looking for include file libintl.h - found
..
[ 59%] Linking CXX executable superpmi
Undefined symbols for architecture x86_64:
  "_libintl_bindtextdomain", referenced from:
      _PAL_BindResources in libcoreclrpal.a(unicode.cpp.o)
  "_libintl_dgettext", referenced from:
      _PAL_GetResourceString in libcoreclrpal.a(unicode.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/ToolBox/superpmi/superpmi/superpmi] Error 1
make[1]: *** [src/ToolBox/superpmi/superpmi/CMakeFiles/superpmi.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
..
make: *** [all] Error 2
Failed to build CoreCLR component.
```

@janvorli investigated:

> I've just noticed that in your "bad" case, the libintl.h is actually found, right? That's causing the trouble since it is not supposed to be present on OSX. The problem is that since we don't expect to find libintl on OSX, we don't try to add the corresponding library for OSX build, which results in the problem you are seeing. 

As more repos are moving to build on the `dnceng` Azure DevOps instance using the machine pools that are set up there, dependencies are being added. ASP.NET Core needs `libintl` installed on Mac agents to build, so we can't just remove it. (Discussion: https://github.com/dotnet/core-eng/issues/4210.)

On the engineering side, build agent pools could be added that don't have `libintl`. It would be more ideal to have a CoreCLR fix. Here are a few ideas:

* Fix to successfully build with and use `libintl`.
* Always ignore `libintl` on Mac builds.
* Add a build flag that specifically disables `libintl` usage and pass the flag when building on `dnceng`.

**Comment by dagood** [comment]
> * Always ignore `libintl` on Mac builds.

I tried this out in source-build with a patch on release/2.1, and got CoreCLR to compile on the Mac agent pool with `libintl`:

https://github.com/dotnet/coreclr/blob/cb730c5c1ec06547505590d7047c00108ac6783f/src/pal/src/configure.cmake#L40

```patch
 check_include_files(pthread_np.h HAVE_PTHREAD_NP_H)
 check_include_files("sys/auxv.h;asm/hwcap.h" HAVE_AUXV_HWCAP_H)
-check_include_files("libintl.h" HAVE_LIBINTL_H)
+
+if(NOT CMAKE_SYSTEM_NAME STREQUAL Darwin)
+  check_include_files("libintl.h" HAVE_LIBINTL_H)
+endif()
 
 if(NOT CMAKE_SYSTEM_NAME STREQUAL FreeBSD AND NOT CMAKE_SYSTEM_NAME STREQUAL NetBSD)
   set(CMAKE_REQUIRED_FLAGS "-ldl")
```

**Comment by janvorli** [comment]
I think that disabling the libintl.h on OSX is the right thing to do. It was actually never intended to be used on OSX, the initial idea was that on OSX, we would use native ways of localization if possible. Btw, the localization support is present since 1.0, but we have never added the actual localized messages to the native runtime, so it is just sitting there.
@dagood, would you mind creating a PR with your fix?

**Comment by dagood** [comment]
Sounds good, that direction makes sense to me. Is it ok if I submit it to `master` and you (or someone else) could port it to `release/2.1`/`2.2`? I'm not too familiar with the merging policy on the release branches right now.

**Comment by UniverseHan** [comment]
Hi @dagood I faced same issue during build coreclr on my MacOS laptop. But it fixed after pull master.

I was struggling with it. But I was not able to find what causes build failure.

How did you know libintl was problem to build this? Could you explain detail for me?

**Comment by dagood** [comment]
In this case, it was just looking at this error message:

```
Undefined symbols for architecture x86_64:
  "_libintl_bindtextdomain", referenced from:
      _PAL_BindResources in libcoreclrpal.a(unicode.cpp.o)
```

and spotting `libintl` in `_libintl_bindtextdomain`. @janvorli knew the rest.

Something that might be throwing you off is that the build doesn't immediately stop when it hits an error: you have to scroll back to find the original error with the useful message.

Also, in case it wasn't clear, the reason pulling fixed the issue is that I merged this fix into `master`: https://github.com/dotnet/coreclr/pull/20094. 😄 This issue is still open because it isn't fixed yet in `release/2.1` and `release/2.2`. (Currently waiting on https://github.com/dotnet/coreclr/pull/20118.)
