### ISSUE TITLE
gtCostsInitialized assertion failed

### ISSUE THREAD

**Issue by mmitche** [dotnet/coreclr#6877]
Expected: True
13:51:02         Actual:   False
13:51:02           D:\j\workspace\x86_ryujit_ch---c998cf3c\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(273276,0): at JIT._Methodical_stringintern__XModuletest2_xmod__XModuletest2_xmod_._Methodical_stringintern__XModuletest2_xmod__XModuletest2_xmod_cmd()
13:52:01 D:\j\workspace\x86_ryujit_ch---c998cf3c\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(320610): error : JIT._Regression_CLR_x86_JIT_V1_M10_b02352_b02352_b02352_._Regression_CLR_x86_JIT_V1_M10_b02352_b02352_b02352_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---c998cf3c\tests\runtest.proj]
13:52:01         
13:52:01         Assert failure(PID 6832 [0x00001ab0], Thread: 7408 [0x1cf0]): Assertion failed 'gtCostsInitialized' in 'DefaultNamespace.cb6054ToByte_all:printoutCoveredMethods()' (IL size 118)
13:52:01         
13:52:01             File: d:\j\workspace\x86_ryujit_ch---c998cf3c\src\jit\gentree.h Line: 464
13:52:01             Image: D:\j\workspace\x86_ryujit_ch---c998cf3c\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe

**Comment by mmitche** [comment]
99% sure this is caused by #6849 @pgavlin.  Recommend we revert for now.

**Comment by pgavlin** [comment]
I have a fix out for this: #6872

**Comment by pgavlin** [comment]
Closed by #6872.
