### ISSUE TITLE
UIntPtrGetHashCode.csproj and IntPtrGetHashCode.csproj have build problems

### ISSUE THREAD

**Issue by ramarag** [dotnet/coreclr#3531]
The build error were introduced in https://github.com/dotnet/coreclr/pull/3511/files

intptrgethashcode.cs(117,17): error CS0103: The name 'retVal' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\intptr\IntPtrGetHashCode.csproj]
intptrgethashcode.cs(125,24): error CS0103: The name 'retVal' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\intptr\IntPtrGetHashCode.csproj]
intptrgethashcode.cs(129,52): error CS0103: The name 'id' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\intptr\IntPtrGetHashCode.csproj]
intptrgethashcode.cs(129,140): error CS0103: The name 'i' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\intptr\IntPtrGetHashCode.csproj]
intptrgethashcode.cs(130,17): error CS0103: The name 'retVal' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\intptr\IntPtrGetHashCode.csproj]
intptrgethashcode.cs(136,13): error CS0103: The name 'retVal' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\intptr\IntPtrGetHashCode.csproj]
intptrgethashcode.cs(138,16): error CS0103: The name 'retVal' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\intptr\IntPtrGetHashCode.csproj]
uintptrgethashcode.cs(169,48): error CS1503: Argument 1: cannot convert from 'long' to 'uint' [E:\git\coreclr\tests\src\CoreMangLib\cti\system\uintptr\UIntPtrGetHashCode.csproj]
uintptrgethashcode.cs(170,48): error CS1503: Argument 1: cannot convert from 'long' to 'uint' [E:\git\coreclr\tests\src\CoreMangLib\cti\system\uintptr\UIntPtrGetHashCode.csproj]
uintptrgethashcode.cs(174,17): error CS0103: The name 'retVal' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\uintptr\UIntPtrGetHashCode.csproj]
uintptrgethashcode.cs(182,24): error CS0103: The name 'retVal' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\uintptr\UIntPtrGetHashCode.csproj]
uintptrgethashcode.cs(186,52): error CS0103: The name 'id' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\uintptr\UIntPtrGetHashCode.csproj]
uintptrgethashcode.cs(186,140): error CS0103: The name 'i' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\uintptr\UIntPtrGetHashCode.csproj]
uintptrgethashcode.cs(187,17): error CS0103: The name 'retVal' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\uintptr\UIntPtrGetHashCode.csproj]
uintptrgethashcode.cs(193,13): error CS0103: The name 'retVal' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\uintptr\UIntPtrGetHashCode.csproj]
uintptrgethashcode.cs(195,16): error CS0103: The name 'retVal' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\uintptr\UIntPtrGetHashCode.csproj]

**Comment by ramarag** [comment]
@vcsjones can you take a look?

**Comment by jkotas** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/3530/files. Thanks @ramarag for taking care of it!

**Comment by ramarag** [comment]
Actually https://github.com/dotnet/coreclr/pull/3530/ does not fix it all, it was the first level of error. The above reported ones surfaced after the fix

**Comment by vcsjones** [comment]
I'm looking into the rest of the errors.

**Comment by ramarag** [comment]
The test project is marked <CLRTestPriority>1</CLRTestPriority>, probably that is the reason the CI did not catch it. The easiest way to build the project is to remove this tag from the .csproj. Then you can directly build the project. 
Or use build.cmd priority 2 from the root [ If you opt for that you don't need to modify the project]

**Comment by vcsjones** [comment]
@ramarag Thanks for the trick on editing the csproj file, that's quite handy over running a full build. I made a PR to correct the build errors.
