### ISSUE TITLE
[ARM32/Linux] cross-architecture component build configuration warning

### ISSUE THREAD

**Issue by hseok-oh** [dotnet/coreclr#8685]
Warning when I try cross-architecture component build configuration only for ARM32/Linux.
```
CMake Warning (dev) at src/utilcode/dac/CMakeLists.txt:8 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.
  The dependency target "coreclrpal" of target "utilcode_dac" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.
CMake Warning (dev) at src/utilcode/dyncrt/CMakeLists.txt:5 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.
   
  The dependency target "coreclrpal" of target "utilcode" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.
CMake Warning (dev) at src/jit/dll/CMakeLists.txt:15 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.
  The dependency target "coreclrpal" of target "clrjit_static" does not
  exist.
This warning is for project developers.  Use -Wno-dev to suppress it.
WARNING: Target "palrt" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
```

**Comment by hseok-oh** [comment]
IMHO, need to check project dependency and modify cross component list for linux.

**Comment by hseok-oh** [comment]
After merging #8687, I get build error in my x64 linux 
```
[  0%] Building CXX object src/pal/src/CMakeFiles/tracepointprovider.dir/misc/tracepointprovider.cpp.o
In file included from /nfs/rbp3/coreclr/src/pal/src/misc/tracepointprovider.cpp:21:
/nfs/rbp3/coreclr/src/pal/src/include/pal/file.h:265:16: error: functions that differ only in their return type cannot be overloaded
size_t __cdecl PAL_fwrite(const void *pvBuffer, size_t nSize, size_t nCount, PAL_FILE *pf);
~~~~~~         ^
/nfs/rbp3/coreclr/src/pal/inc/pal.h:6100:26: note: previous declaration is here
PALIMPORT size_t __cdecl PAL_fwrite(const void *, size_t, size_t, PAL_FILE *);
          ~~~~~~         ^
In file included from /nfs/rbp3/coreclr/src/pal/src/misc/tracepointprovider.cpp:24:
/nfs/rbp3/coreclr/src/pal/src/include/pal/malloc.hpp:33:5: error: conflicting types for 'PAL_realloc'
    PAL_realloc(
    ^
/nfs/rbp3/coreclr/src/pal/inc/pal.h:6013:26: note: previous declaration is here
PALIMPORT void * __cdecl realloc(void *, size_t);
                         ^
/nfs/rbp3/coreclr/src/pal/inc/pal.h:5669:23: note: expanded from macro 'realloc'
#define realloc       PAL_realloc
                      ^
In file included from /nfs/rbp3/coreclr/src/pal/src/misc/tracepointprovider.cpp:24:
/nfs/rbp3/coreclr/src/pal/src/include/pal/malloc.hpp:40:5: error: conflicting types for 'PAL_malloc'
    PAL_malloc(
    ^
/nfs/rbp3/coreclr/src/pal/inc/pal.h:6011:26: note: previous declaration is here
PALIMPORT void * __cdecl malloc(size_t);
                         ^
/nfs/rbp3/coreclr/src/pal/inc/pal.h:5721:23: note: expanded from macro 'malloc'
#define malloc        PAL_malloc
                      ^
3 errors generated.
make[2]: *** [src/pal/src/CMakeFiles/tracepointprovider.dir/misc/tracepointprovider.cpp.o] Error 1
make[1]: *** [src/pal/src/CMakeFiles/tracepointprovider.dir/all] Error 2
```

We need x86 cross compilation to build cross-architecture component in x64 environment, because it needs system library header files for 32bit linux.

**Comment by seanshpark** [comment]
@hseok-oh , can you add a comment about your build host environment and target platform/architecture?

**Comment by hseok-oh** [comment]
@seanshpark host: x64 ubuntu 14.04 / target: arm(hardfp) linux.
But cross-architecture component will run in host linux machine.

**Comment by hseok-oh** [comment]
fixed by #8687, #8722
