### PR TITLE
Update Buildtools and Roslyn

### PR DESCRIPTION
**Pull request by joperezr**
cc: @jkotas @VSadov @stephentoub 

Isolating the Update of buildtools from #14159 which includes using the new roslyn compiler. I'm isolating just buildtools update so that we can see if CI errors are triggered at all with the new compiler.

### CODE REVIEW

**Comment by jkotas** [comment]
Fails on `Microsoft.Net.Compilers is only supported on MSBuild v15.0 and above ` error during test build

**Comment by tannergooding** [comment]
The relevant check is here: https://github.com/dotnet/roslyn/blob/d4dab355b96955aca5b4b0ebf6282575fad78ba8/build/NuGetAdditionalFiles/Microsoft.Net.Compilers.props#L12

Looks like @jaredpar updated the validation to include MSBuild 14, but I'm not sure that is correct (@agocke might be able to comment).

**Comment by VSadov** [comment]
Seems like similar to the issues in https://github.com/dotnet/buildtools/pull/1661

I am not sure why this is happening. 
Considering the infrastructure issues and difficulties with getting builds, we need some kind of a workaround.

**Comment by tannergooding** [comment]
Ok, So I went and talked with @agocke and it sounds like the change was made because there are some new MSBuild properties and/or tasks that we actually depend on.

@jaredpar is the only one that could definitely confirm that, but I believe he is OOF right now.

It sounds like the easiest fix is to move the build machines to just use VS2017 by default.

**Comment by agocke** [comment]
The errors on Mac and Ubuntu confuse me. MSBuild 14 has never shipped on Ubuntu or OSX. What's going on there?

**Comment by agocke** [comment]
Jared left the following comment in https://github.com/dotnet/roslyn/issues/19128:

`But our actual MSBuild task that drives the compiler is dependent on MSBuild 15.0 for C# 7.0 and above.`

**Comment by joperezr** [comment]
I forgot to add an extra condition that will fix the msbuild 14.0 issues. We already do this in corefx here: https://github.com/dotnet/corefx/blob/master/dir.props#L301-L302

**Comment by joperezr** [comment]
@dotnet/dnceng not sure it this is something that you guys should look at but should we be using msbuild 15.0 on CI now?

**Comment by jkotas** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test 

(timeout)

**Comment by jkotas** [comment]
The Windows_NT x64 test build is timing out (happened multiple times).

**Comment by joperezr** [comment]
@jkotas have you seen this in other PRs in coreclr or is it just with mine?  cc: @dotnet/dnceng

**Comment by joperezr** [comment]
It looks as though the build was still doing stuff, and it wasn't stuck. If you check the times it looks like seconds before it was still printing things and then it just passed the timeout. Might it be that we have to increase the timeout?

**Comment by joperezr** [comment]
I chatted with @dotnet/dnceng team offline, we are seeing this issue only on my PR because of the perf hit of not being able to use the compiler server when building with MSBuild 14.0. I will work with them to try to get at least that leg upgraded to MSBuild 15.0 so that I can get a green CI job. Once that is done, I'll comeback here and merge the PR.

**Comment by joperezr** [comment]
@dotnet-bot test this please (specs on CI machines have been updated)

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by ahsonkhan** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test
@dotnet-bot test CentOS7.1 x64 Release Priority 1 Build and Test

**Comment by ahsonkhan** [comment]
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test
@dotnet-bot test CentOS7.1 x64 Release Priority 1 Build and Test

**Comment by joperezr** [comment]
@dotnet/dnceng looks like the builds are still timing out even with the fix to  use VS2017. Also looks like CentOS7.1 started failing as well. Any ideas of what might be going on(slow machines, or maybe some recent change on the hardware in them)?

**Comment by mmitche** [comment]
@joperezr The machines are the same sku as before.   Are you sure the build is using VS2017?

Btw the centos failed because it runs the windows build to get the tests.

**Comment by jkotas** [comment]
CoreCLR build will default to VS2015 when both VS2015 and VS2017 are installed. You need to make a fix in the build scripts similar to https://github.com/dotnet/corert/pull/4341/ . And once you do that, you will likely hit the problem with old CMake version in the image.

**Comment by joperezr** [comment]
>CoreCLR build will default to VS2015 when both VS2015 and VS2017 are installed

@jkotas 
I believe that is not true. If you look at https://github.com/dotnet/coreclr/blob/master/run.cmd#L19-L38 it seems like we will try to use MSBuild 15.0 instead of 14.0 if both are installed, which is why I thought that just installing SxS should just fix the issue. Is there a different place where we force to use 14.0 over 15.0 on this repo?

**Comment by joperezr** [comment]
I think I know what the problem is. By looking locally, it seems that the installation of VS 2017 won't set `VS150COMNTOOLS` as an environment variable. ONLY if you are running on a developer command prompt 2017 then would that variable be set, so our logic of prefering VS version is wrong. Looks like there is a tool that does the right thing for locating the latest version here: https://github.com/Microsoft/vswhere

**Comment by joperezr** [comment]
> And once you do that, you will likely hit the problem with old CMake version in the image.

As usual, you were right @jkotas and predicted what would happen 😄 

@dotnet/dnceng @mmitche can we update the version of CMake that we have installed on the build machines? That should hopefully get us unblocked.

**Comment by joperezr** [comment]
@dotnet-bot test this please (CMake has been updated now)

**Comment by joperezr** [comment]
Looks like the builds that were hitting time outs are working now, but I'm hitting two new issues, one on Ubuntu and one on the Windows arm64 cross build. @jkotas I'm not too familiar with the native build of coreclr, do you know what might be going on?

**Comment by jkotas** [comment]
arm64 build failures should be fixed by https://github.com/dotnet/coreclr/pull/14286/

**Comment by jkotas** [comment]
@dotnet-bot test Ubuntu arm64 Cross Debug Build please
@dotnet-bot test Windows_NT arm64 Cross Debug Build please

**Comment by joperezr** [comment]
looks like Ubuntu is now hitting a different issue..
`/mnt/j/workspace/dotnet_coreclr/master/arm64_debug_small_page_size_prtest/src/pal/src/misc/sysinfo.cpp:492:48: error: no matching function for call to 'max'`

**Comment by jkotas** [comment]
```
/mnt/j/workspace/dotnet_coreclr/master/arm64_debug_small_page_size_prtest/src/pal/src/misc/sysinfo.cpp:492:48: error: no matching function for call to 'max'
```

@janvorli Looks like a fallout from your change

**Comment by jkotas** [comment]
The Ubuntu arm64 build break should not be blocking merging this change.

**Comment by janvorli** [comment]
@jkotas right, I'll fix it in a minute.

**Comment by joperezr** [comment]
Merging now since as adviced we won't wait for Ubuntu arm64 build to work. Thanks a lot for your help getting this in guys.

File: run.cmd [hunk 1]
```diff
@@ -16,27 +16,21 @@ setlocal
...
-  :NoVS
+set _VSWHERE="%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
+if exist %_VSWHERE% (
+  for /f "usebackq tokens=*" %%i in (`%_VSWHERE% -latest -property installationPath`) do set _VSCOMNTOOLS=%%i\Common7\Tools
+)
+if not exist "%_VSCOMNTOOLS%" set _VSCOMNTOOLS=%VS140COMNTOOLS%
+if not exist "%_VSCOMNTOOLS%" (
   echo Error: Visual Studio 2015 or 2017 required.
-  echo        https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md for build instructions.
+  echo        Please see https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md for build instructions.
```
Comment (RussKeldorph) [inline run.cmd]: @joperezr Was the change to refer coreclr users to corefx docs intentional or copy/paste error?

Comment (joperezr) [reply run.cmd]: Oops copy paste error, good catch! I'll fix this.
