### PR TITLE
Handle glibc sys/sysctl.h deprecation

### LINKED ISSUE #27008: coreclr fails to build with glibc 2.30 due to sys/sysctl.h deprecation
Building coreclr on Fedora 32, with glibc 2.30 gives me:

```
In file included from /coreclr/src/pal/src/misc/sysinfo.cpp:32:
/usr/include/sys/sysctl.h:21:2: error: "The <sys/sysctl.h> header is deprecated and will be removed." [-Werror,-W#warnings]
#warning "The <sys/sysctl.h> header is deprecated and will be removed."
 ^
1 error generated.
make[2]: *** [src/pal/src/CMakeFiles/coreclrpal.dir/build.make:687: src/pal/src/CMakeFiles/coreclrpal.dir/misc/sysinfo.cpp.o] Error 1
```

This is a change in glibc 2.30. See http://patches-tcwg.linaro.org/patch/19443/ for their discussion. This is affecting other projects too, for example https://bugs.launchpad.net/ubuntu/+source/squid/+bug/1843325

### PR DESCRIPTION
**Pull request by omajid**
glibc has deprecated sys/sysctl.h:

    In file included from /coreclr/src/pal/src/misc/sysinfo.cpp:32:
    /usr/include/sys/sysctl.h:21:2: error: "The <sys/sysctl.h> header is deprecated and will be removed." [-Werror,-W#warnings]
    #warning "The <sys/sysctl.h> header is deprecated and will be removed."
     ^
    1 error generated.

Fix that by preferring sysconf and only including sys/sysctl.h if HAVE_SYSCONF is not true. This mirrors the order of the implementation code in this file (sysinfo.cpp) which checks for HAVE_SYSCONF before HAVE_SYSCTL.

Fixes #27008

### CODE REVIEW

**Comment by omajid** [comment]
The windows NT failure looks unrelated (this is PAL code, not used on Windows, right?) Anyone willing to merge this?
