### PR TITLE
Delete null comparisons of non-null arguments

### PR DESCRIPTION
**Pull request by am11**
gcc 8 complains that these conditions cannot be met, as argument is
nonnull, e.g.:

> error: nonnull argument 'this' compared to NULL
> [-Werror=nonnull-compare]

### CODE REVIEW

**Comment by am11** [comment]
cc @jkotas

**Comment by danmosemsft** [comment]
Why did people write these checks originally?

**Comment by am11** [comment]
@danmosemsft, calling a non-static function with nullptr is an undefined behavior in C++. Newer version of gcc raises warning with pedantic mode and -Wall (v6 doesn't complain, v8 does). In the modified files, some call-sites are checking for null and some aren't, I have fixed the ones detected by GNU analysis (and removed `-Wno-nonnull-compare` in my other branch that builds CoreCLR with GCC v8).

File: src/inc/corcompile.h [hunk 1]
```diff
@@ -905,22 +905,16 @@ class CorProfileData
 
     struct CORBBTPROF_TOKEN_INFO *  GetTokenFlagsData(SectionFormat section)
     {
-        if (this == NULL)
```
Comment (jkotas) [inline src/inc/corcompile.h]: I do not see what makes these safe to delete.

File: src/vm/object.cpp [hunk 2]
```diff
@@ -604,17 +599,18 @@ VOID Object::ValidateInner(BOOL bDeep, BOOL bVerifyNextHeader, BOOL bVerifySyncB
...
             CHECK_AND_TEAR_DOWN(bSmallObjectHeapPtr || bLargeObjectHeapPtr);
         }
 
         lastTest = 3;
 
         if (bDeep)
         {
-            CHECK_AND_TEAR_DOWN(GetHeader()->Validate(bVerifySyncBlock));
+            PTR_ObjHeader ptrObjHeader = GetHeader();
+            CHECK_AND_TEAR_DOWN(ptrObjHeader && ptrObjHeader->Validate(bVerifySyncBlock));
```
Comment (jkotas) [inline src/vm/object.cpp]: This is not necessary. Code above ensures that this is non-null.

File: src/vm/object.cpp [hunk 3]
```diff
@@ -646,7 +642,8 @@ VOID Object::ValidateInner(BOOL bDeep, BOOL bVerifyNextHeader, BOOL bVerifySyncB
             if ((nextObj != NULL) &&
                 (nextObj->GetGCSafeMethodTable() != g_pFreeObjectMethodTable))
             {
-                CHECK_AND_TEAR_DOWN(nextObj->GetHeader()->Validate(FALSE));
+                PTR_ObjHeader  ptrObjHeader = nextObj->GetHeader();
+                CHECK_AND_TEAR_DOWN(ptrObjHeader && ptrObjHeader->Validate(FALSE));
```
Comment (jkotas) [inline src/vm/object.cpp]: Dtto

**Comment by jkotas** [comment]
We are close to 3.0 release. This change has non-trivial risk of fallout.

Thank you for doing this cleanup. We will take after the last snap for 3.0 (in a month or so) and have a runway to shake out the potential bugs.

File: src/vm/object.cpp (hunk 2 above)
Comment (am11) [reply src/vm/object.cpp]: Removed the check.

File: src/inc/corcompile.h (hunk 1 above)
Comment (am11) [reply src/inc/corcompile.h]: I was relying on tests to validate these changes. This combination worked for various configurations (and passed 41 CI checks). I can all null checks on all callsites, if it is not considered safe.

Comment (jkotas) [reply src/inc/corcompile.h]: I think that would be better.

E.g. It think `Module::GetProfileData()` in `Module::ExpandAll` can return NULL that this check was protecting against. We may be missing coverage for these paths in the CI.

**Comment by janvorli** [comment]
@am11 we can also remove the following option with your change:
https://github.com/dotnet/coreclr/blob/447670fb7cfbf0812faa7cbf4792195d56844de5/configurecompiler.cmake#L467-L468

File: src/debug/ee/debugger.cpp [hunk 4]
```diff
@@ -14247,7 +14247,7 @@ Debugger::InsertToMethodInfoList( DebuggerMethodInfo *dmi )
         return (hr);
     }
 
-    DebuggerMethodInfo *dmiPrev = m_pMethodInfos->GetMethodInfo(dmi->m_module, dmi->m_token);
+    DebuggerMethodInfo *dmiPrev = m_pMethodInfos ? m_pMethodInfos->GetMethodInfo(dmi->m_module, dmi->m_token) : NULL;
```
Comment (jkotas) [inline src/debug/ee/debugger.cpp]: CheckInitMethodInfoTable above ensures that `m_pMethodInfos` is non-null. The null check is not necessary here.

File: src/debug/ee/debugger.cpp [hunk 5]
```diff
@@ -14590,7 +14590,7 @@ void Debugger::SendRawLogMessage(
                  pAppDomain);
 
     ipce->FirstLogMessage.iLevel = iLevel;
-    ipce->FirstLogMessage.szCategory.SetString(pCategory->GetUnicode());
+    ipce->FirstLogMessage.szCategory.SetString(pCategory ? pCategory->GetUnicode() : NULL);
```
Comment (jkotas) [inline src/debug/ee/debugger.cpp]: This is only called from one place in `DebugDebugger::Log` that never passes in NULL. The null check is not necessary here.

File: src/jit/codegen.h [hunk 6]
```diff
@@ -1449,7 +1449,6 @@ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 
         static const GenConditionDesc& Get(GenCondition condition)
         {
-            assert(condition.GetCode() < _countof(map));
```
Comment (jkotas) [inline src/jit/codegen.h]: This is good assert to have. What if `map` definition changes?

File: src/jit/gentree.h [hunk 7]
```diff
@@ -5725,7 +5725,6 @@ struct GenCondition
         };
         // clang-format on
 
-        assert(m_code < _countof(names));
```
Comment (jkotas) [inline src/jit/gentree.h]: Same here

File: src/vm/ceeload.cpp [hunk 8]
```diff
@@ -7722,8 +7722,8 @@ void Module::ExpandAll(DataImage *image)
     // Record references to all of the hot methods specifiled by MethodProfilingData array
     // We call MethodReferencedByCompiledCode to indicate that we plan on compiling this method
     //
-    CORBBTPROF_TOKEN_INFO * pMethodProfilingData = profileData->GetTokenFlagsData(MethodProfilingData);
-    DWORD                   cMethodProfilingData = profileData->GetTokenFlagsCount(MethodProfilingData);
+    CORBBTPROF_TOKEN_INFO * pMethodProfilingData = profileData ? profileData->GetTokenFlagsData(MethodProfilingData) : NULL;
```
Comment (jkotas) [inline src/vm/ceeload.cpp]: I would be better to have just one `if (profileData != NULL)` that protects the two loops below instead of checking every time `profileData` is accessed.

File: src/vm/ceeload.cpp [hunk 9]
```diff
@@ -9099,8 +9099,8 @@ void Module::Arrange(DataImage *image)
         //
         // Place hot type structues in the order specifiled by TypeProfilingData array
         //
-        CORBBTPROF_TOKEN_INFO * pTypeProfilingData = profileData->GetTokenFlagsData(TypeProfilingData);
-        DWORD                   cTypeProfilingData = profileData->GetTokenFlagsCount(TypeProfilingData);
+        CORBBTPROF_TOKEN_INFO * pTypeProfilingData = profileData ? profileData->GetTokenFlagsData(TypeProfilingData) : NULL;
```
Comment (jkotas) [inline src/vm/ceeload.cpp]: `profileData` was checked for non-null a few lines above. No need to check again.

File: src/vm/clrprivbinderwinrt.cpp [hunk 10]
```diff
@@ -791,7 +791,7 @@ CLRPrivBinderWinRT::GetFileNameListForNamespace(
         if (cFileNames > 0)
         {
             _ASSERTE(cFileNames == 1); //only support mapping to one file in coregen
-            hFileNameList.InsertTail(rgFileNames->GetUnicode());
+            hFileNameList.InsertTail(rgFileNames ? rgFileNames->GetUnicode() : NULL);
```
Comment (jkotas) [inline src/vm/clrprivbinderwinrt.cpp]: Null check not necessary here. `CrossgenRoResolveNamespace` never returns null strings when `cFileNames > 0`.

File: src/vm/eventtrace.cpp [hunk 11]
```diff
@@ -6230,9 +6230,9 @@ VOID ETW::MethodLog::SendMethodJitStartEvent(MethodDesc *pMethodDesc, SString *n
 
         // fire method information
         /* prepare events args for ETW and ETM */
-        szDtraceOutput1 = (PCWSTR)namespaceOrClassName->GetUnicode();
-        szDtraceOutput2 = (PCWSTR)methodName->GetUnicode();
-        szDtraceOutput3 = (PCWSTR)methodSignature->GetUnicode();
+        szDtraceOutput1 = namespaceOrClassName ? (PCWSTR)namespaceOrClassName->GetUnicode() : NULL;
```
Comment (jkotas) [inline src/vm/eventtrace.cpp]: The block right before this guarantees that `namespaceOrClassName` is non-null.

File: src/vm/eventtrace.cpp [hunk 12]
```diff
@@ -6382,9 +6382,9 @@ VOID ETW::MethodLog::SendMethodEvent(MethodDesc *pMethodDesc, DWORD dwEventOptio
             methodName = &tMethodName;
             methodSignature = &tMethodSignature;
         }
-        pNamespaceName = (PWCHAR)namespaceOrClassName->GetUnicode();
-        pMethodName = (PWCHAR)methodName->GetUnicode();
-        pMethodSignature = (PWCHAR)methodSignature->GetUnicode();
+        pNamespaceName = namespaceOrClassName ? (PWCHAR)namespaceOrClassName->GetUnicode() : NULL;
```
Comment (jkotas) [inline src/vm/eventtrace.cpp]: Same here

File: src/vm/stubhelpers.cpp [hunk 13]
```diff
@@ -59,7 +59,10 @@ void StubHelpers::ValidateObjectInternal(Object *pObjUNSAFE, BOOL fValidateNextO
 
 	// validate the object - there's no need to validate next object's
 	// header since we validate the next object explicitly below
-	pObjUNSAFE->Validate(/*bDeep=*/ TRUE, /*bVerifyNextHeader=*/ FALSE, /*bVerifySyncBlock=*/ TRUE);
+	if (pObjUNSAFE)
+	{
+		pObjUNSAFE->Validate(/*bDeep=*/ TRUE, /*bVerifyNextHeader=*/ FALSE, /*bVerifySyncBlock=*/ TRUE);
```
Comment (jkotas) [inline src/vm/stubhelpers.cpp]: Indentation looks off

File: src/vm/typeparse.cpp [hunk 14]
```diff
@@ -31,7 +31,7 @@ SString* TypeName::ToString(SString* pBuf, BOOL bAssemblySpec, BOOL bSignature,
     TypeNameBuilder tnb(pBuf);
 
     for (COUNT_T i = 0; i < m_names.GetCount(); i ++)
-        tnb.AddName(m_names[i]->GetUnicode());
+        tnb.AddName(m_names[i] ? m_names[i]->GetUnicode() : NULL);
```
Comment (jkotas) [inline src/vm/typeparse.cpp]: Null check not necessary. Elements added to `m_names` are never null.

File: src/vm/typeparse.cpp [hunk 15]
```diff
@@ -180,7 +180,7 @@ void QCALLTYPE TypeName::QGetNames(TypeName * pTypeName, QCall::ObjectHandleOnSt
 
         for (COUNT_T i = 0; i < count; i++)
         {
-            STRINGREF str = StringObject::NewString(names[i]->GetUnicode());
+            STRINGREF str = StringObject::NewString(names[i] ? names[i]->GetUnicode() : NULL);
```
Comment (jkotas) [inline src/vm/typeparse.cpp]: Same

File: src/vm/util.cpp [hunk 16]
```diff
@@ -1388,7 +1388,7 @@ BOOL ReportEventCLR(
     GCX_PREEMP();
 
     SString buff;
-    buff.Printf(W(".NET Runtime version %s - %s"), VER_FILEVERSION_STR_L, message->GetUnicode());
+    buff.Printf(W(".NET Runtime version %s - %s"), VER_FILEVERSION_STR_L, message ? message->GetUnicode() : NULL);
```
Comment (jkotas) [inline src/vm/util.cpp]: This method does not seem to be called from anywhere. It would be better to delete it.

File: src/vm/typestring.cpp [hunk 17]
```diff
@@ -610,7 +610,7 @@ HRESULT TypeNameBuilder::ToString(BSTR* pszStringRepresentation)
     if (m_instNesting)
         return Fail();
 
-    *pszStringRepresentation = SysAllocString(m_pStr->GetUnicode());
+    *pszStringRepresentation = SysAllocString(m_pStr ? m_pStr->GetUnicode() : NULL);
```
Comment (jkotas) [inline src/vm/typestring.cpp]: null check not necessary.

File: src/jit/codegen.h (hunk 6 above)
Comment (am11) [reply src/jit/codegen.h]: Most of these were removed for clang 3.9 in fdf04aa. Without this commit (and with `tutological-compare` warning enabled), gcc5-8 and clang6-8 are satisfied. I can move `tautological-compare` changes in a separate PR and keep this one for nonnull-comparison (which mainly focuses on `this == null`)?

I think the warning was `Wtautological-constant-out-of-range-compare`, as it leads to dead code. 

> What if map definition changes?

I think that is the reason why they have stopped complaining about it in clang6. :)

File: src/vm/typeparse.cpp [hunk 18]
```diff
@@ -1321,7 +1325,8 @@ TypeHandle TypeName::GetTypeFromAsm()
     if (th.IsNull() && bThrowIfNotFound)
     {
         StackSString buf;
-        LPCWSTR wszName = ToString(&buf)->GetUnicode();
+        SString* bufString = ToString(&buf);
```
Comment (jkotas) [inline src/vm/typeparse.cpp]: Was this refactoring required for some reason, or is it just a cosmetic change?

Comment (am11) [reply src/vm/typeparse.cpp]: It is a leftover, I will revert it. I first added null checks in all usages, and this refactoring prevented calling ToString() twice. In next compile, the null check was reverted but code refactoring remained.

File: src/jit/codegen.h (hunk 6 above)
Comment (jkotas) [reply src/jit/codegen.h]: > I think that is the reason why they have stopped complaining about it in clang6

I would keep `tautological-compare` warning disabled then since it is not helping in its current state.

File: src/vm/stubhelpers.cpp (hunk 13 above)
Comment (am11) [reply src/vm/stubhelpers.cpp]: This one is tab-indented as the nearby lines.

File: src/vm/util.cpp (hunk 16 above)
Comment (am11) [reply src/vm/util.cpp]: Removed `ReportEventCLR` from both cpp and hpp.

File: src/jit/codegen.h (hunk 6 above)
Comment (am11) [reply src/jit/codegen.h]: @jkotas, @janvorli, I have disabled `tautological-compare` only where compiler is too sensitive (feature detection in `configure.cmake` and used on `configurecompiler.cmake`). The introspection check succeeds on clang v6+ (tested with v6 and latest stable v8, both succeeded) and fails on v3.9 to v5.x on Linux/FreeBSD and corresponding versions of Apple Clang (which has different versioning scheme). The reason to keep it for higher versions of clang is that it has provided some useful dead-code detection: f84aa60943b36d0840bc337e39dbd87ce7af38f8.

Comment (janvorli) [reply src/jit/codegen.h]: It seems that the tautological-compare warning is actually a superset of several tautological warnings. Here is the hierarchy extracted from https://github.com/llvm-mirror/clang/blob/d8066f9602863a39f208a52ca3be977c46a5d0f0/include/clang/Basic/DiagnosticGroups.td:
* tautological-compare
  * tautological-pointer-compare
  * tautological-constant-compare
    * tautological-constant-out-of-range-compare
  * tautological-overlap-compare
  * tautological-undefined-compare

So maybe we can use the more fine-grained one(s) to disable what we really need.

Comment (am11) [reply src/jit/codegen.h]: Unfortunately, the top-level warning is also thrown by Clang 3.9, as well as the deepest `tautological-constant-out-of-range-compare`:

```
/datadrive/projects/coreclr2/src/md/enc/stgio.cpp:645:47: error: comparison of unsigned expression < 0 is always false [-Werror,-Wtautological-compare]
                if (cbRtn > m_cbData || cbRtn < 0)
                                        ~~~~~ ^ ~
...
/datadrive/projects/coreclr2/src/jit/_typeinfo.h:334:23: error: result of comparison of constant 63 with expression of type 'ti_types' is always true [-Werror,-Wtautological-constant-out-of-range-compare]
        assert(tiType <= TI_FLAG_DATA_MASK);
        ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
```

Comment (jkotas) [reply src/jit/codegen.h]: I think it is fine to compile the code-base with higher warning levels from time to time and fix what makes sense. But I do not think we should bother with having these questionable warnings enabled by default. They just cause pain when they are enabled by default.

Comment (am11) [reply src/jit/codegen.h]: @jkotas, since <kbd>[release/3.0](https://github.com/dotnet/coreclr/tree/release/3.0)</kbd> has been branched out, if master is getting post-3.0 fixes could this PR be defrosted?
I have some Solaris patches lining up which are done with gcc7 on top of these changes.

Comment (jkotas) [reply src/jit/codegen.h]: We are still merging all fixes from master to release/3.0. release/3.0 is used to build the official preview builds while there is ongoing work on 3.0 in master.

Comment (am11) [reply src/jit/codegen.h]: In the current shape of this change, there seems to be no room for fallout, compared to other changes been made to master. Do you still think it has to made or can this be merged?

File: configurecompiler.cmake [hunk 19]
```diff
@@ -464,8 +464,15 @@ if (CLR_CMAKE_PLATFORM_UNIX)
     add_compile_options(-Wno-unused-private-field)
     # Explicit constructor calls are not supported by clang (this->ClassName::ClassName())
     add_compile_options(-Wno-microsoft)
-    # This warning is caused by comparing 'this' to NULL
-    add_compile_options(-Wno-tautological-compare)
+
+    if (NOT COMPILER_HAS_ROBUST_TAUTOLOGICAL_COMPARISON_CHECKS)
```
Comment (jkotas) [inline configurecompiler.cmake]: I do not think we want to be doing configure checks for warning levels. I do not think that the complexity is worth it.

File: src/jit/codegen.h (hunk 6 above)
Comment (jkotas) [reply src/jit/codegen.h]: > there seems to be no room for fallout

I think it still has opportunity for fallout. It is easy to miss cases in changes like these.

> other changes been made to master

The changes going to master at this point should be either important for 3.0 or no risk. I am sorry, but this one is not important for 3.0.

Comment (am11) [reply src/jit/codegen.h]: It's OK. I am unblocked with change made in master disabling this warning for gcc. This was anyway nice to have cleanup. Thanks for your review.

**Comment by jkotas** [comment]
@am11 Have you deleted the branch on purpose that closed the PR? I think this was a good change.

**Comment by am11** [comment]
Yes, I have synchronized my fork with dotnet/coreclr remote. I merged master to my solaris/gcc port branch, it does not require this change anymore, the warning from gcc in description has been disabled. We can resume the PR after 3.0 is shipped.
