### ISSUE TITLE
[GCSample] Cleanup warnings and add it to the build

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#1548]
GC sample is not part of the regular build because of it builds with a lot of warnings. We should clean them up and add it to the build.

**Comment by jkotas** [comment]
#1547

**Comment by mattwarren** [comment]
I don't know if it's supported or not, but when I ran the sample in Visual Studio, I had to make a few changes to get it to build. You can see them in [this commit](https://github.com/mattwarren/GCSample/commit/16534fd414deaea8e59cbb77f009c140375ef227). 

Obviously some of the changes are not proper fixes, i.e. [commenting out `GCToEEInterface::SyncBlockCacheWeakPtrScan()`](https://github.com/mattwarren/GCSample/commit/16534fd414deaea8e59cbb77f009c140375ef227#diff-10fcdb4865726b979af3a89eea66eec8R1584) to prevent `unresolved external symbol` errors. But my C/C++ skills are pretty basic, so I don't know what the correct fixes are?

BTW thanks to whoever wrote the GC Sample, I've found it very useful

**Comment by jkotas** [comment]
I have made the proper fixes for the VS project build breaks in https://github.com/dotnet/coreclr/pull/2582.

> thanks to whoever wrote the GC Sample

That's me :-)

**Comment by jkotas** [comment]
Closing this issue - GCSample was added to the build by @janvorli in #2244

**Comment by mattwarren** [comment]
Thanks for fixing it, I'll try out the new version in the next couple of day.

> > thanks to whoever wrote the GC Sample

> That's me :-)

Well thank-you, plus thanks in advance for the extra work you are going to do, like #1551
