### PR TITLE
Fix desktop retail build break

### PR DESCRIPTION
**Pull request by briansull**
error C2220: warning treated as error -
from jit\codegencommon.cpp(11228): warning C4702: unreachable code

### CODE REVIEW

**Comment by briansull** [comment]
Introduced with #14883

**Comment by briansull** [comment]
@sdmaclea @jashook PTAL

**Comment by sdmaclea** [comment]
@briansull Oops.  Sorry about that.  Completely missed it during code review.   LGTM.
