### PR TITLE
fix sysctlt compilation error on FreeBSD

### PR DESCRIPTION
**Pull request by wfurt**
This is regression caused by #27048 and build fails like:
```
[ 28%] Built target utilcodestaticnohost
/home/furt/git/coreclr/src/pal/src/misc/sysinfo.cpp:382:10: error: use of undeclared identifier 'sysctlnametomib'
    rc = sysctlnametomib("vm.swap_info", mib, &length);
         ^
[ 35%] Built target cee_dac
/home/furt/git/coreclr/src/pal/src/misc/sysinfo.cpp:390:18: error: use of undeclared identifier 'sysctl'
            rc = sysctl(mib, 3, &xsw, &length, NULL, 0);
                 ^
/home/furt/git/coreclr/src/pal/src/misc/sysinfo.cpp:599:30: error: use of undeclared identifier 'sysctlbyname'
        const bool success = sysctlbyname("hw.l3cachesize", &cacheSizeFromSysctl, &sz, nullptr, 0) == 0
                             ^
/home/furt/git/coreclr/src/pal/src/misc/sysinfo.cpp:600:16: error: use of undeclared identifier 'sysctlbyname'
            || sysctlbyname("hw.l2cachesize", &cacheSizeFromSysctl, &sz, nullptr, 0) == 0
               ^
/home/furt/git/coreclr/src/pal/src/misc/sysinfo.cpp:601:16: error: use of undeclared identifier 'sysctlbyname'
            || sysctlbyname("hw.l1dcachesize", &cacheSizeFromSysctl, &sz, nullptr, 0) == 0;
[ 35%] Generating eventpipe/eventpipehelpers.cpp, eventpipe/dotnetruntime.cpp, eventpipe/dotnetruntimerundown.cpp, eventpipe/dotnetruntimestress.cpp, eventpipe/dotnetruntimeprivate.cpp

```

The problem is that FreeBSD has HAVE_SYSCONF and that seems mutually elusive in includes but later on used with different guard.  Maybe it would be better to set HAVE_SYSCONF=0 on Linux if we want to avoid usage of it.

This is minimal change to fix compilation while preserving spirit of #27048.
Note that FreeBSD does not have vm.swap_info. We will probably need separate effort to find some equivalent. 

cc: @omajid

### CODE REVIEW

**Comment by omajid** [comment]
@wfurt Thanks for fixing this. Should we add FreeBSD (and/or other BSDs) to our CI system?

**Comment by wfurt** [comment]
> @wfurt Thanks for fixing this. Should we add FreeBSD (and/or other BSDs) to our CI system?

That is long story. 
FreeBSD used to be there but unfortunately it was removed as there is no official Azure or .NET support.

File: src/pal/src/misc/sysinfo.cpp [hunk 1]
```diff
@@ -31,9 +31,12 @@ Revision History:
 
 #if HAVE_SYSCONF
 // <unistd.h> already included above
-#elif HAVE_SYSCTL
+#endif
+#if HAVE_SYSCTL && not defined(__linux__)
```
Comment (janvorli) [inline src/pal/src/misc/sysinfo.cpp]: Can you please use `!` instead of `not` here and below?

Comment (wfurt) [reply src/pal/src/misc/sysinfo.cpp]: updated.
