### ISSUE TITLE
[Linux_rhel6 x64 ] Build product failure after #25909

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#25990]
https://dev.azure.com/dnceng/public/_build/results?buildId=292830&view=logs
```
/__w/1/s/src/pal/src/exception/remote-unwind.cpp:976:51: error: expected ')'
        TRACE("ELF: phdr %p type %d (%x) vaddr %" PRIxA " memsz %" PRIxA " paddr %" PRIxA " filesz %" PRIxA " offset %" PRIxA " align %" PRIxA "\n",
                                                  ^
/__w/1/s/src/pal/src/exception/remote-unwind.cpp:82:20: note: expanded from macro 'PRIxA'
#define PRIxA PRIA PRIx
                   ^
/__w/1/s/src/pal/src/exception/remote-unwind.cpp:78:14: note: expanded from macro 'PRIx'
#define PRIx PRIx64
             ^
/__w/1/s/src/pal/src/exception/remote-unwind.cpp:976:9: note: to match this '('
        TRACE("ELF: phdr %p type %d (%x) vaddr %" PRIxA " memsz %" PRIxA " paddr %" PRIxA " filesz %" PRIxA " offset %" PRIxA " align %" PRIxA "\n",
        ^
/__w/1/s/src/pal/src/include/pal/dbgmsg.h:269:5: note: expanded from macro 'TRACE'
    DBG_PRINTF(DLI_TRACE,defdbgchan,TRUE)
    ^
/__w/1/s/src/pal/src/include/pal/dbgmsg.h:325:9: note: expanded from macro 'DBG_PRINTF'
        DBG_PRINTF2
        ^
/__w/1/s/src/pal/src/include/pal/dbgmsg.h:328:17: note: expanded from macro 'DBG_PRINTF2'
      DBG_printf(__chanid,__levid,__bHeader,__FUNCTION__,__FILE__,__LINE__,__VA_ARGS__);\
                ^
1 error generated.
```

@mikem8361

**Comment by mikem8361** [comment]
I have a fix coming.

**Comment by mikem8361** [comment]
Fixed.
