### PR TITLE
Fix build on glibc versions prior to 2.19

### PR DESCRIPTION
**Pull request by soimort**
Related issues: #300 , [#177#issuecomment-75372528](https://github.com/dotnet/coreclr/issues/177#issuecomment-75372528)

Feature test macro `_DEFAULT_SOURCE` is available since glibc 2.19 [[1]](http://savannah.gnu.org/forum/forum.php?forum_id=7882). On glibc versions prior to that, `clang -D_DEFAULT_SOURCE -Wall -std=c11` fails to compile with `<libunwind.h>`, since it uses `stack_t`, which is a System V-derived definition and not contained in ISO C11 standard.

The `stack_t` type has been defined in POSIX.1-2008 [[2]](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/signal.h.html). To equivalently utilize the same features in glibc prior to 2.19, I suggest that we explicitly add `-D_POSIX_C_SOURCE=200809L` to specify POSIX.1-2008 conformance. This change shall enable building CoreCLR on GNU/Linux distros with older glibc versions pre-installed, such as Debian wheezy (libc 2.13) and CentOS 7 (glibc 2.17), without breaking anything on glib 2.19+. (Changing `-std=c11` to `-std=gnu11` as in #300 , as well as switching to `_GNU_SOURCE`, seem not preferable because they've enabled GNU extensions, which are unnecessary.)

### CODE REVIEW

**Comment by jkotas** [comment]
@soimort Thanks submitting the PR. Unfortunately, it breaks the build on MacOS:

src/pal/src/file/file.cpp:1828:33: error: no member named 'st_ctimensec' in 'stat'; did you mean 'st_ctimespec'?

Could you please take a look? You can find the full logs under the "Details" link above.

**Comment by jkotas** [comment]
LGTM

**Comment by soimort** [comment]
Things like `st_atimensec`, `st_mtimensec`, and `st_ctimensec` seem to be non-standard definitions, defined in glibc along with `st_atime`, etc. In POSIX 2008 these are replaced by `struct timespec st_atim` and others. [[1]](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_stat.h.html#tag_13_62) On glibc they are still usable unless XSI is enabled (`_DEFAULT_SOURCE` does not allow for any X/Open extensions), however, on Darwin, which has SUSv3 conformance but not full POSIX 2008 conformance, will fail to compile that one under strict POSIX mode.

With no `_POSIX_C_SOURCE` defined on Mac OS X, full namespace is enabled so code made use of `st_atimensec` can be built normally.

Reference: https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man5/compat.5.html

**Comment by jkotas** [comment]
Thanks for the contribution!
