### ISSUE TITLE
[R2R/x86] tracing/tracevalidation/rundown fails

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#16710]
[ci job](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_checked_windows_nt_r2r/) shows that x86_checked_windows_nt_r2r leg was green ([last green build](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_checked_windows_nt_r2r/730/) 28.02.2018 14:17), then it showed build failures and then it started to show [tracing/tracevalidation/rundown test failure](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_checked_windows_nt_r2r/734/).

Looks like  PR #16667 introduced this, @nategraf could you please look?

**Comment by nategraf** [comment]
I'll check it out

**Comment by nategraf** [comment]
It's also [failing in x64](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_r2r/968/testReport/junit/tracing_tracevalidation/_rundown_rundown_rundown_/_rundown_rundown_rundown_cmd/) but passing for [non-r2r builds](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_checked_windows_nt/3993/testReport/tracing_tracevalidation/). So this seems to be specific to when R2R is used. Is it possible to build with R2R on my local dev machine?

**Comment by nategraf** [comment]
@brianrob It seems `Microsoft.Diagnostics.Tracing.TraceEvent` is not appearing in `AssemblyDCStop` events, but `runtime` and `System.Runtime` are. Is there some straightforward explanation for why this would not happen with R2R?

**Comment by brianrob** [comment]
I don't see anything obvious - R2R really shouldn't have anything to do with this.  But obviously something proper here.  We should debug this.  I'm going to try the repro tool and see if I can get a machine that way for simplicity.

**Comment by sandreenko** [comment]
@nategraf Yes, you can run r2r on your machine:
```
build.cmd checked x86  -priority=1 // to build x86 with all tests
tests\runtest.cmd checked x86 crossgen runcrossgentests // to crossgen assemblies and run r2r tests
```

then you can run only this test in r2r mode with env variable `set RunCrossGen=true` and run this test cmd file.

**Comment by brianrob** [comment]
@sandreenko it looks like the repro tool isn't going to work because it looks like there is another earlier break: https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_checked_windows_nt_r2r/753/

```
d:\j\workspace\x86_checked_w---fb5c73ad\src\jit\hwintrinsiclistxarch.h(197): error C2065: 'HW_Flag_BaseTypeFromArg': undeclared identifier (compiling source file D:\j\workspace\x86_checked_w---fb5c73ad\src\jit\hwintrinsicxarch.cpp) [D:\j\workspace\x86_checked_w---fb5c73ad\bin\obj\Windows_NT.x86.Checked\src\jit\standalone\clrjit.vcxproj]
```

**Comment by brianrob** [comment]
@nategraf if you are able to reproduce this locally that's probably going to be easier until this compilation failure is fixed.  If you are able to reproduce this and want help debugging, just let me know.

**Comment by brianrob** [comment]
Looks like the compilation failure is being addressed by https://github.com/dotnet/coreclr/pull/16715.

**Comment by sandreenko** [comment]
Thanks @nategraf
