### PR TITLE
Fix desktop build break

### PR DESCRIPTION
**Pull request by echesakovMSFT**
Fix desktop build break
codegenlegacy.cpp(16025): warning C4389: '!=' : signed/unsigned mismatch
codegenlegacy.cpp(16025): error C2220: warning treated as error - no 'object' file generated

Introduced in #15524

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
@CarolEidt @dotnet/jit-contrib Thanks for letting me know about build break and sorry about that! PTAL

**Comment by BruceForstall** [comment]
Seems like you should cast lvFldOffset to size_t, to match bytesToBeCopied.
