### PR TITLE
Fix build with Clang 6.0 and enable build with Clang 5.0

### LINKED ISSUE #16850: Build failed with Clang 6.0
I am getting some errors on ubuntu when building coreclr with clang 6.0.

```sh
[  0%] Building CXX object src/corefx/System.Globalization.Native/CMakeFiles/System.Globalization.Native_Static.dir/__/__/__/version.cpp.o
[  0%] Building CXX object src/corefx/System.Globalization.Native/CMakeFiles/System.Globalization.Native.dir/__/__/__/version.cpp.o
[  0%] Linking CXX static library System.Globalization.Native.a
[  0%] Linking CXX shared library System.Globalization.Native.so
[  0%] Built target System.Globalization.Native_Static
Scanning dependencies of target coreclrpal
Verifying System.Globalization.Native dependencies
[  0%] Built target System.Globalization.Native
Scanning dependencies of target eventprovider
[  0%] Building CXX object src/pal/src/eventprovider/CMakeFiles/eventprovider.dir/lttng/eventprovdotnetruntime.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/file.cpp.o
In file included from /coreclr/bin/obj/Linux.x64.Debug/eventing/eventprovider/lttng/eventprovdotnetruntime.cpp:24:
In file included from /coreclr/bin/obj/Linux.x64.Debug/eventing/eventprovider/lttng/tpdotnetruntime.h:14:
In file included from /coreclr/src/pal/inc/rt/palrt.h:1617:
/coreclr/src/pal/inc/rt/ntimage.h:47:10: error: the current #pragma pack aligment value is modified in the included file
      [-Werror,-Wpragma-pack]
#include "pshpack4.h"                   // 4 byte packing is the default
         ^
/coreclr/src/pal/inc/rt/pshpack4.h:36:9: note: previous '#pragma pack' directive that modifies alignment is here
#pragma pack(4)
        ^
In file included from /coreclr/bin/obj/Linux.x64.Debug/eventing/eventprovider/lttng/eventprovdotnetruntime.cpp:24:
In file included from /coreclr/bin/obj/Linux.x64.Debug/eventing/eventprovider/lttng/tpdotnetruntime.h:14:
In file included from /coreclr/src/pal/inc/rt/palrt.h:1617:
/coreclr/src/pal/inc/rt/ntimage.h:55:10: error: the current #pragma pack aligment value is modified in the included file
      [-Werror,-Wpragma-pack]
#include "pshpack2.h"                   // 16 bit headers are 2 byte packed
         ^
/coreclr/src/pal/inc/rt/pshpack2.h:35:9: note: previous '#pragma pack' directive that modifies alignment is here
#pragma pack(2)
        ^
In file included from /coreclr/bin/obj/Linux.x64.Debug/eventing/eventprovider/lttng/eventprovdotnetruntime.cpp:24:
In file included from /coreclr/bin/obj/Linux.x64.Debug/eventing/eventprovider/lttng/tpdotnetruntime.h:14:
In file included from /coreclr/src/pal/inc/rt/palrt.h:1617:
/coreclr/src/pal/inc/rt/ntimage.h:177:10: error: the current #pragma pack aligment value is modified in the included
      file [-Werror,-Wpragma-pack]
#include "poppack.h"                    // Back to 4 byte packing
         ^
/coreclr/src/pal/inc/rt/poppack.h:37:9: note: previous '#pragma pack' directive that modifies alignment is here
#pragma pack()
        ^
In file included from /coreclr/bin/obj/Linux.x64.Debug/eventing/eventprovider/lttng/eventprovdotnetruntime.cpp:24:
In file included from /coreclr/bin/obj/Linux.x64.Debug/eventing/eventprovider/lttng/tpdotnetruntime.h:14:
In file included from /coreclr/src/pal/inc/rt/palrt.h:1617:
/coreclr/src/pal/inc/rt/ntimage.h:571:10: error: the current #pragma pack aligment value is modified in the included
      file [-Werror,-Wpragma-pack]
#include "pshpack2.h"                       // Symbols, relocs, and linenumbers are 2 byte packed
         ^
/coreclr/src/pal/inc/rt/pshpack2.h:35:9: note: previous '#pragma pack' directive that modifies alignment is here
#pragma pack(2)
        ^
In file included from /coreclr/bin/obj/Linux.x64.Debug/eventing/eventprovider/lttng/eventprovdotnetruntime.cpp:24:
In file included from /coreclr/bin/obj/Linux.x64.Debug/eventing/eventprovider/lttng/tpdotnetruntime.h:14:
In file included from /coreclr/src/pal/inc/rt/palrt.h:1617:
/coreclr/src/pal/inc/rt/ntimage.h:773:10: error: the current #pragma pack aligment value is modified in the included
      file [-Werror,-Wpragma-pack]
#include "poppack.h"
         ^
/coreclr/src/pal/inc/rt/poppack.h:37:9: note: previous '#pragma pack' directive that modifies alignment is here
#pragma pack()
        ^
In file included from /coreclr/bin/obj/Linux.x64.Debug/eventing/eventprovider/lttng/eventprovdotnetruntime.cpp:24:
In file included from /coreclr/bin/obj/Linux.x64.Debug/eventing/eventprovider/lttng/tpdotnetruntime.h:14:
In file included from /coreclr/src/pal/inc/rt/palrt.h:1617:
/coreclr/src/pal/inc/rt/ntimage.h:1227:10: error: the current #pragma pack aligment value is modified in the included
      file [-Werror,-Wpragma-pack]
#include "pshpack8.h"                       // Use align 8 for the 64-bit IAT.
         ^
/coreclr/src/pal/inc/rt/pshpack8.h:36:9: note: previous '#pragma pack' directive that modifies alignment is here
#pragma pack(8)
        ^
In file included from /coreclr/bin/obj/Linux.x64.Debug/eventing/eventprovider/lttng/eventprovdotnetruntime.cpp:24:
In file included from /coreclr/bin/obj/Linux.x64.Debug/eventing/eventprovider/lttng/tpdotnetruntime.h:14:
In file included from /coreclr/src/pal/inc/rt/palrt.h:1617:
/coreclr/src/pal/inc/rt/ntimage.h:1239:10: error: the current #pragma pack aligment value is modified in the included
      file [-Werror,-Wpragma-pack]
#include "poppack.h"                        // Back to 4 byte packing
         ^
/coreclr/src/pal/inc/rt/poppack.h:37:9: note: previous '#pragma pack' directive that modifies alignment is here
#pragma pack()
        ^
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/filecrt.cpp.o
7 errors generated.
src/pal/src/eventprovider/CMakeFiles/eventprovider.dir/build.make:62: recipe for target 'src/pal/src/eventprovider/CMakeFiles/eventprovider.dir/lttng/eventprovdotnetruntime.cpp.o' failed
make[2]: *** [src/pal/src/eventprovider/CMakeFiles/eventprovider.dir/lttng/eventprovdotnetruntime.cpp.o] Error 1
CMakeFiles/Makefile2:353: recipe for target 'src/pal/src/eventprovider/CMakeFiles/eventprovider.dir/all' failed
make[1]: *** [src/pal/src/eventprovider/CMakeFiles/eventprovider.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/lstr.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/malloc.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/math.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/mbstring.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/misc.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/misctls.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/path.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/printf.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/printfcpp.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/silent_printf.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/string.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/stringtls.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/thread.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/wchar.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/wchartls.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/debug/debug.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/exception/seh.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/exception/signal.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/exception/remote-unwind.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/file/directory.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/file/file.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/file/filetime.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/file/find.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/file/path.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/handlemgr/handleapi.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/handlemgr/handlemgr.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/init/pal.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/init/sxs.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/loader/module.cpp.o
[  1%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/loader/modulename.cpp.o
[  1%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/locale/unicode.cpp.o
[  1%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/locale/unicode_data.cpp.o
[  1%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/locale/utf8.cpp.o
[  1%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/map/common.cpp.o
[  1%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/map/map.cpp.o
[  1%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/map/virtual.cpp.o
In file included from /coreclr/src/pal/src/map/map.cpp:40:
/coreclr/src/pal/inc/rt/ntimage.h:47:10: error: the current #pragma pack aligment value is modified in the included file
      [-Werror,-Wpragma-pack]
#include "pshpack4.h"                   // 4 byte packing is the default
         ^
/coreclr/src/pal/inc/rt/pshpack4.h:36:9: note: previous '#pragma pack' directive that modifies alignment is here
#pragma pack(4)
        ^
In file included from /coreclr/src/pal/src/map/map.cpp:40:
/coreclr/src/pal/inc/rt/ntimage.h:55:10: error: the current #pragma pack aligment value is modified in the included file
      [-Werror,-Wpragma-pack]
#include "pshpack2.h"                   // 16 bit headers are 2 byte packed
         ^
/coreclr/src/pal/inc/rt/pshpack2.h:35:9: note: previous '#pragma pack' directive that modifies alignment is here
#pragma pack(2)
        ^
In file included from /coreclr/src/pal/src/map/map.cpp:40:
/coreclr/src/pal/inc/rt/ntimage.h:177:10: error: the current #pragma pack aligment value is modified in the included
      file [-Werror,-Wpragma-pack]
#include "poppack.h"                    // Back to 4 byte packing
         ^
/coreclr/src/pal/inc/rt/poppack.h:37:9: note: previous '#pragma pack' directive that modifies alignment is here
#pragma pack()
        ^
In file included from /coreclr/src/pal/src/map/map.cpp:40:
/coreclr/src/pal/inc/rt/ntimage.h:571:10: error: the current #pragma pack aligment value is modified in the included
      file [-Werror,-Wpragma-pack]
#include "pshpack2.h"                       // Symbols, relocs, and linenumbers are 2 byte packed
         ^
/coreclr/src/pal/inc/rt/pshpack2.h:35:9: note: previous '#pragma pack' directive that modifies alignment is here
#pragma pack(2)
        ^
In file included from /coreclr/src/pal/src/map/map.cpp:40:
/coreclr/src/pal/inc/rt/ntimage.h:773:10: error: the current #pragma pack aligment value is modified in the included
      file [-Werror,-Wpragma-pack]
#include "poppack.h"
         ^
/coreclr/src/pal/inc/rt/poppack.h:37:9: note: previous '#pragma pack' directive that modifies alignment is here
#pragma pack()
        ^
```

### PR DESCRIPTION
**Pull request by janvorli**
Close #16850

### CODE REVIEW

**Comment by janvorli** [comment]
cc: @kasper3

**Comment by RussKeldorph** [comment]
Is the _Pragma (MSVC __pragma) keyword ubiquitous enough to replace the old pushpck/poppck mechanism?

**Comment by janvorli** [comment]
@RussKeldorph interesting, I didn't know it exists. Seems to be implemented in clang too. It seems it would make sense to eventually change it to that. Although, if some of the files where we would need to change that are processed by MIDL on Windows too, it would make it problematic.

File: src/ToolBox/SOS/lldbplugin/CMakeLists.txt [hunk 1]
```diff
@@ -76,6 +76,7 @@ endif()
 # If the file in a directory is found the result is stored in the variable and the search will not be repeated unless the variable is cleared.
 find_path(LLDB_H "lldb/API/LLDB.h" PATHS "${WITH_LLDB_INCLUDES}" NO_DEFAULT_PATH)
 find_path(LLDB_H "lldb/API/LLDB.h")
+find_path(LLDB_H "lldb/API/LLDB.h" PATHS "/usr/lib/llvm-6.0/include")
 find_path(LLDB_H "lldb/API/LLDB.h" PATHS "/usr/lib/llvm-4.0/include")
```
Comment (kasper3) [inline src/ToolBox/SOS/lldbplugin/CMakeLists.txt]: Should this also include llvm-5.0/include? Same for above in `find_library` call.
Btw, did you get LLDB.h? I almost installed all the 6.0 packages but couldn't find it. Do you know which package installed LLDB.h?

Comment (kasper3) [reply src/ToolBox/SOS/lldbplugin/CMakeLists.txt]: I built with `./build.sh cmakeargs -DENABLE_LLDBPLUGIN=0` because of absence of LLDB.h

Comment (janvorli) [reply src/ToolBox/SOS/lldbplugin/CMakeLists.txt]: I have looked at the build log and it has actually picked LLDB.h from an older installed version. I've tried to install all the packages available for llvm 6.0 and that version of the header didn't get installed. I don't know if that's an intention or mistake on the llvm side. The llvm 5.0 still contains it.

> Should this also include llvm-5.0/include

I haven't originally added it since there used to be  a bug in clang 5.0 preventing compilation of our stuff. I have thought that it was not fixed yet, but I've just tried the 5.0 package and it worked. So I am going to augment this change to add support for 5.0 too so that we don't skip that version.

Comment (kasper3) [reply src/ToolBox/SOS/lldbplugin/CMakeLists.txt]: That bug was fixed in 5.0.1 😄
I asked about it today in #lldb channel over at IRC, maybe @krytarowski can provide some insights on why LLDB.h is missing from https://apt.llvm.org liblldb-6.0-dev package. Is it a bug in packaging since it is available in release_60 branch https://github.com/llvm-mirror/lldb/blob/release_60/include/lldb/API/LLDB.h?

Comment (krytarowski) [reply src/ToolBox/SOS/lldbplugin/CMakeLists.txt]: I don't use apt.llvm.org.
