### ISSUE TITLE
FreeBSD port team needs to document LLDB-setup

### ISSUE THREAD

**Issue by josteink** [dotnet/coreclr#797]
We should either have a documented (version-controlled?) script/gist which can be used (and re-used) to get the correct LLDB-version built and installed, or we need to get an official package for this which can be installed like any of our other dependencies.

While we can rely on external wikis and end-user copy-pasting, I would rather have something more closely tied to this project for increased traceability.

Getting a simple and repeatable LLDB installation will not only help getting work done(tm), but might also assist [getting a complete CI-build](https://github.com/dotnet/coreclr/issues/793): In lack of LLDB, we're currently we're not the SOS LLDB-plugin.

As for LLDB version... Should we aim for 3.5? 3.6? or latest? Does it matter?

I think Linux settled for LLDB 3.6, despite building with LLVM 3.5 because LLDB 3.5 (from official packages) was "buggy" on Ubuntu, but I don't know the full back-story for this. Are there any similar concerns which should govern which version we use for FreeBSD?

@emaste : You were briefly involved with getting LLDB into the pkg-repository. Any progress or news since last time? If you've made any progress, what version(s) are you currently working with?

**Comment by janhenke** [comment]
I would prefer to go for the latest release version, which is 3.6. Since LLDB is still a relatively young project, new releases should add more fixes.
We can also already build with LLVM/CLang 3.6 on FreeBSD. My PR for that landed already in main, just run `./build.sh clang3.6` and it will pick 3.6 instead of 3.5 for building.

**Comment by josteink** [comment]
@ajensenwaud Have you tried building coreclr with your locally built LLDB? Does it try to build the SOS-plugin, or is further work needed to look into that?

**Comment by ajensenwaud** [comment]
No, not yet. Do we need to link it against LLDB? I can certainly try so, but am unsure where that is done. 

LLDB is happy to debug the corerun executable, so it seems to work.

**Comment by janhenke** [comment]
The SOS plugin for LLDB needs the LLDB header/library to link against. Can you install your installation to `/usr/local/`?

**Comment by ajensenwaud** [comment]
Sure, give me a few secs.

**Comment by josteink** [comment]
@ajensenwaud After getting LLDB installed proper, the build no longer complains about missing LLDB.

I'm pretty sure we'll get the SOS LLDB debugging extensions as well from the build now. That might come in handy further down the road as we try to debug this thing :)

**Comment by josteink** [comment]
Actually. That *breaks* the build. Seems to be a problem with the SOS debugger:

````
[100%] Building CXX object src/ToolBox/SOS/lldbplugin/CMakeFiles/sosplugin.dir/soscommand.cpp.o
/home/josteink/build/coreclr/src/ToolBox/SOS/lldbplugin/debugclient.cpp:103:5: error: use of undeclared identifier 'va_start'
    va_start (args, format);
    ^
/home/josteink/build/coreclr/src/ToolBox/SOS/lldbplugin/debugclient.cpp:105:5: error: use of undeclared identifier 'va_end'
    va_end (args);
    ^
/home/josteink/build/coreclr/src/ToolBox/SOS/lldbplugin/debugclient.cpp:119:5: error: use of undeclared identifier 'va_copy'
    va_copy (args_copy, args);
    ^
/home/josteink/build/coreclr/src/ToolBox/SOS/lldbplugin/debugclient.cpp:136:15: error: no type named 'free' in the global namespace
            ::free (str_ptr);
            ~~^
/home/josteink/build/coreclr/src/ToolBox/SOS/lldbplugin/debugclient.cpp:144:5: error: use of undeclared identifier 'va_end'
    va_end (args_copy);
    ^
/home/josteink/build/coreclr/src/ToolBox/SOS/lldbplugin/debugclient.cpp:163:5: error: use of undeclared identifier 'va_start'
    va_start (args, format);
    ^
/home/josteink/build/coreclr/src/ToolBox/SOS/lldbplugin/debugclient.cpp:165:5: error: use of undeclared identifier 'va_end'
    va_end (args);
    ^
7 errors generated.
--- src/ToolBox/SOS/lldbplugin/CMakeFiles/sosplugin.dir/debugclient.cpp.o ---
````

Looks like we still have some work to do.

**Comment by ajensenwaud** [comment]
I just fixed the above build error in https://github.com/dotnet/coreclr/pull/812 -- build now works with lldbplugin.

**Comment by josteink** [comment]
Great stuff. Now we should get back to the main issue: Getting the LLDB-setup documented.

Did you save your (exact) steps in a script, so they can be reused by other potential collaberators, or even for CI-purposes?

**Comment by ajensenwaud** [comment]
I did not write a script but can very quickly document it. Let me write it up today.

Anders Jensen-Waud

**Comment by ajensenwaud** [comment]
I have put up a simple build and install script for LLDB here: https://github.com/ajensenwaud/freebsd-dotnet-misc/blob/master/install-lldb.sh

We could include this as part of the build+install documentation for FreeBSD -- please let me know and I will write it up.

**Comment by taylorjonl** [comment]
What are the memory requirements for this?  I tried running it on a 2gb VM and it ran OOM.  I will update you when I try doing this again but I only have a laptop and it has limited RAM.

**Comment by taylorjonl** [comment]
I increased the VM to 4gb of RAM and it completed successfully, so we may want to figure out exactly how much RAM is needed and include it any any documentation.

**Comment by taylorjonl** [comment]
In the end I had to increase the VM to 8gb of RAM and >40gb of disk, not sure which made it work but that is where I ended.

**Comment by josteink** [comment]
If those are the LLBB requirements, getting it pre-compiled as a package really will make it *much* more accessible. No word from @emaste yet though.

**Comment by josteink** [comment]
@ajensenwaud Thanks for the script. Great stuff. In the absence of an official LLDB-package, I think that should be linked to in the FreeBSD build-instructions, and submitted as a PR to dotnet/master.

That would in my eyes be more than good enough to close this issue.

**Comment by tony** [comment]
For LLDB, 3.6 sounds good, since we have those versions in ports anyway. 

Related: https://github.com/dotnet/coreclr/issues/940 I'm still troubleshooting issues on the script.

**Comment by emaste** [comment]
LLDB is now available in the llvm-devel port / package as of ports tree SVN r393042. This is a development snapshot and not a release though; I'll still try to get a release package done, probably for 3.7.

https://svnweb.freebsd.org/ports?view=revision&revision=393042

**Comment by josteink** [comment]
Awesome work! That will probably make bootstrapping a build-environment a lot easier, especially on weaker machines where the memory-constraint easily becomes a show-stopper.

Thanks for your effort :)

**Comment by emaste** [comment]
The llvm-devel change was @brooksdavis and he deserves the credit.

The trick with a standalone LLDB package is that building LLDB requires LLVM and Clang source and ends up rebuilding a lot of it.

**Comment by brooksdavis** [comment]
devel/llvm37 contains contains lldb from 3.7 (currently 3.7.0-RC1).  I don't plan to add 3.6 support but could if it were a serious blocker.

**Comment by emaste** [comment]
I think that's fine. LLDB's still moving fairly quickly, and there are a lot of improvements in each new version.

**Comment by tony** [comment]
@emaste : I recognize your name from a few bugzilla threads we were on. Nice to see you here.

@brooksdavis: Thank you for this. I tried to build lldb a couple of times over the past 2 weeks but have failed with various compilation errors.

I am going to give this a shot and report back tomorrow

**Comment by josteink** [comment]
@tony if you get this working, feel free to send in a PR with an up to date and accurate build process using the new LLDB package.

Such a PR should probably close this issue once and for all :)

**Comment by tony** [comment]
I'm not one to fall off the face of the Earth. But I should probably give some explanation to the lack of communication.

Over the past few weeks I have been failing to compile lldb from trunk. Previously I had no troubles whatsoever.  Also, I have been experiencing strange issues with ``make buildworld`` and compiling various things.

Up until a few hours ago, even the new ``devel/llvm37`` port would fail to build.

On #freebsd the info I got back was my system was borked in someway. Sure, poudriere compiled the devel port perfectly. But I wanted to find what the heck was happening  so other people don't get tripped up and waste their time.

I tried downloading ``portupgrade`` which includes a tool called ``pkg_which``. Eventually it lead me consulting with ``/usr/local/include/clang-c``, ``/usr/local/include/clang``, ``/usr/local/include/llvm``, ``/usr/local/include/llvm-c``.  I removed those directories and things are building fine.

That may seem like a painfully obvious oversight, I probably passed by them 10+ times and never had a second thought because they didn't feel out of place. 

@josteink will do

**Comment by brooksdavis** [comment]
@tony It's been quite a while since ports or packages of llvm installed bits in /usr/local/include.  If I see multiple reports of the issue I'll add guards to the ports to fail if it finds llvm bits in /usr/local/include.

**Comment by tony** [comment]
@jim-p's https://gist.github.com/jim-p/10140152 also had a similar issue
building a different port because of /usr/local/include/llvm-c headers.

It's possible others wondered themselves into the situation but don't want
to lose face by overlooking something so "simple" hiding in plain sight.
The other thing is I was on the verge of following advice from #freebsd and
reinstalling my system without figuring out the specific issue.

I think a mechanism to catch it would be a wise idea if it was possible, in
lieu of that I'm examining if we can mention / have already mentioned it in
our handbooks somewhere.
