### ISSUE TITLE
[armel/Tizen] Broken crossgen2 build

### ISSUE THREAD

**Issue by alpencolt** [dotnet/coreclr#27199]
`crossgen2` build for `armel` is broken after #26960 with error
```
 CSC : error CS2001: Source file '/var/lib/jenkins/workspace/netcore/nightly_master/build_coreclr_rpm_stress/repo/code/artifacts/obj/System.Private.CoreLib/armel/Release/../../../Eventing/arm/Release/NativeRuntimeEventSource.cs' could not be found. [/var/lib/jenkins/workspace/netcore/nightly_master/build_coreclr_rpm_stress/repo/code/src/System.Private.CoreLib/System.Private.CoreLib.csproj]
```
This PR change location of `NativeRuntimeEventSource.cs` which located now in `armel` subfolder: https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/System.Private.CoreLib.csproj#L318 but being searched in `arm`.

Reason is different values in `$(Platfrom)` and `$(BuildArch)` variables:
https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/System.Private.CoreLib.csproj#L40

cc @davidwrighton @jkotas 
cc @o-piskunov

**Comment by alpencolt** [comment]
Closed via  #27227
