### ISSUE TITLE
ARM/Linux: failed to detect ucol_setMaxVariable

### ISSUE THREAD

**Issue by seanshpark** [dotnet/coreclr#5324]
I have 
```
coreclr/src/corefx/System.Globalization.Native/collation.cpp:282:9: error: 'ucol_setVariableTop_55' is
deprecated [-Werror,-Wdeprecated-declarations]
        ucol_setVariableTop(pClonedCollator, ignoreSymbolsVariableTop, 1, pErr);
```
with current master branch, cross building `ARM/Linux` for `RPi2`, with `ubuntu 15.10 (wily)` RootFS image, using `Clang 3.8.1`. Found out it was after #5309 merge.

In the configuration step, I see
```
-- Looking for ucol_setMaxVariable
-- Looking for ucol_setMaxVariable - not found
```
and with below change in `src/corefx/System.Globalization.Native/configure.cmake`
```
 " HAVE_UDAT_STANDALONE_SHORTER_WEEKDAYS)
 
 if(NOT CLR_CMAKE_PLATFORM_DARWIN)
-    set(CMAKE_REQUIRED_LIBRARIES ${ICUUC} ${ICUI18N})
+    # set(CMAKE_REQUIRED_LIBRARIES ${ICUUC} ${ICUI18N})
 else()
     set(CMAKE_REQUIRED_LIBRARIES ${ICUCORE})
 endif()
```
configuration is
```
-- Looking for ucol_setMaxVariable
-- Looking for ucol_setMaxVariable - found
```
OK and build is also OK.

If dump`${ICUUC} ${ICUI18N}` values I see two file path
```
/home/maxwell/zarm-rootfs-wily/usr/lib/arm-linux-gnueabihf/libicuuc.so
/home/maxwell/zarm-rootfs-wily/usr/lib/arm-linux-gnueabihf/libicui18n.so
```
and these files seems OK, so don't understand why it fails to use `ucol_setMaxVariable`

My colleague has no problem with default Ubuntu 14.04 with Clang 3.6.

**Comment by jasonwilliams200OK** [comment]
@seanhpark, could you share `coreclr/bin/obj/Linux.x64.Debug/CMakeFiles/CMakeError.log` via https://gist.github.com?

**Comment by jasonwilliams200OK** [comment]
Also can you give this patch a try:

```diff
--- a/src/corefx/System.Globalization.Native/configure.cmake
+++ b/src/corefx/System.Globalization.Native/configure.cmake
@@ -9,9 +9,9 @@ CHECK_CXX_SOURCE_COMPILES("
 " HAVE_UDAT_STANDALONE_SHORTER_WEEKDAYS)
 
 if(NOT CLR_CMAKE_PLATFORM_DARWIN)
-    set(CMAKE_REQUIRED_LIBRARIES ${ICUUC} ${ICUI18N})
+    list(APPEND CMAKE_REQUIRED_LIBRARIES ${ICUUC} ${ICUI18N})
 else()
-    set(CMAKE_REQUIRED_LIBRARIES ${ICUCORE})
+    list(APPEND CMAKE_REQUIRED_LIBRARIES ${ICUCORE})
 endif()
 
 check_symbol_exists(
@@ -19,7 +19,7 @@ check_symbol_exists(
     "unicode/ucol.h"
     HAVE_SET_MAX_VARIABLE)
 
-unset(CMAKE_REQUIRED_LIBRARIES)
+list(REMOVE_ITEM CMAKE_REQUIRED_LIBRARIES ${ICUUC} ${ICUI18N})
 unset(CMAKE_REQUIRED_INCLUDES)
```

**Comment by seanshpark** [comment]
@jasonwilliams200OK , I could not create a gist cause of firewall. This is what I got in `CMakeError.log` for `ucol_setMaxVariable`
```
Determining if the ucol_setMaxVariable exist failed with the following output:
Change Dir: /home/maxwell/coreclr/bin/obj/Linux.arm.Debug/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/make "cmTryCompileExec40186386/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec40186386.dir/build.make CMakeFiles/cmTryCompileExec40186386.dir/build
make[1]: Entering directory `/home/maxwell/coreclr/bin/obj/Linux.arm.Debug/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/maxwell/coreclr/bin/obj/Linux.arm.Debug/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec40186386.dir/CheckSymbolExists.c.o
/home/maxwell/bin/llvm/bin/clang-3.8   -Wall -std=c11  -I/home/maxwell/zarm-rootfs-wily/usr/include/arm-linux-gnueabihf -I/usr/local/opt/icu4c/include    -target armv7-linux-gnueabihf -mthumb -mfpu=vfpv3 --sysroot=/home/maxwell/zarm-rootfs-wily -o CMakeFiles/cmTryCompileExec40186386.dir/CheckSymbolExists.c.o   -c /home/maxwell/coreclr/bin/obj/Linux.arm.Debug/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTryCompileExec40186386
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec40186386.dir/link.txt --verbose=1
/home/maxwell/bin/llvm/bin/clang-3.8   -Wall -std=c11        -target arm-linux-gnueabihf -B /home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf -L/home/maxwell/zarm-rootfs-wily/lib/arm-linux-gnueabihf --sysroot=/home/maxwell/zarm-rootfs-wily CMakeFiles/cmTryCompileExec40186386.dir/CheckSymbolExists.c.o  -o cmTryCompileExec40186386 -rdynamic -licuuc -licui18n 
/home/maxwell/bin/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-ld: warning: libicudata.so.55, needed by /home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so, not found (try using -rpath or -rpath-link)
/home/maxwell/bin/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-ld: warning: libdl.so.2, needed by /home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so, not found (try using -rpath or -rpath-link)
/home/maxwell/bin/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-ld: warning: libstdc++.so.6, needed by /home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so, not found (try using -rpath or -rpath-link)
/home/maxwell/bin/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-ld: warning: libm.so.6, needed by /home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so, not found (try using -rpath or -rpath-link)
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicui18n.so: undefined reference to `asin@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `log@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `operator delete(void*)@GLIBCXX_3.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `fmod@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicui18n.so: undefined reference to `sin@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `vtable for __cxxabiv1::__class_type_info@CXXABI_1.3'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `ceil@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicui18n.so: undefined reference to `acos@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicui18n.so: undefined reference to `tan@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `__cxa_call_unexpected@CXXABI_1.3'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `floor@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `__gxx_personality_v0@CXXABI_1.3'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicui18n.so: undefined reference to `atan@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `__cxa_end_cleanup@CXXABI_1.3'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicui18n.so: undefined reference to `atan2@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicui18n.so: undefined reference to `cos@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `pow@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `dlsym@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `dlclose@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `__dynamic_cast@CXXABI_1.3'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `vtable for __cxxabiv1::__si_class_type_info@CXXABI_1.3'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `icudt55_dat'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `vtable for __cxxabiv1::__vmi_class_type_info@CXXABI_1.3'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `__cxa_pure_virtual@CXXABI_1.3'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicui18n.so: undefined reference to `sincos@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `std::type_info::operator==(std::type_info const&) const@GLIBCXX_3.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `dlopen@GLIBC_2.4'
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cmTryCompileExec40186386] Error 1
make[1]: Leaving directory `/home/maxwell/coreclr/bin/obj/Linux.arm.Debug/CMakeFiles/CMakeTmp'
make: *** [cmTryCompileExec40186386/fast] Error 2

File /home/maxwell/coreclr/bin/obj/Linux.arm.Debug/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <unicode/ucol.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef ucol_setMaxVariable
  return ((int*)(&ucol_setMaxVariable))[argc];
#else
  (void)argc;
  return 0;
#endif
}
```

**Comment by seanshpark** [comment]
And with the patch, also got same error. I'll try to find out why linker cannot find libc and libm functions.
Thank you.

**Comment by seanshpark** [comment]
I've found the cause. It was my local `/home/maxwell/bin/arm-linux-gnueabihf` 5.2.1 compiler installed in my home bin folder. When I switch to system default gcc-4.8, it builds with success.
I don't know why the 5.2.1 linker could not find it's own library for this case.

**Comment by jasonwilliams200OK** [comment]
Looks like it is not accounting for the linked libs absolute path: `-rdynamic -licuuc -licui18n`. On my machine it looks like `-rdynamic /usr/lib64/libicuuc.so /usr/lib64/libicui18n.so`. Seems like we would need to temporary configure rpath for `CMAKE_REQUIRED_LIBRARIES`.

---

Separate from finding the rpath solution for linker, could you try (this will most probably not fix the problem, just curious how CMakeError log differs with this path if you may):

```diff
--- a/src/corefx/System.Globalization.Native/configure.cmake
+++ b/src/corefx/System.Globalization.Native/configure.cmake
@@ -9,8 +9,13 @@ CHECK_CXX_SOURCE_COMPILES("
 " HAVE_UDAT_STANDALONE_SHORTER_WEEKDAYS)
 
 if(NOT CLR_CMAKE_PLATFORM_DARWIN)
+    get_filename_component(ICUUC_DIR ${ICUUC} PATH)
+    get_filename_component(ICUI18N_DIR ${ICUI18N} PATH)
+    set(CMAKE_REQUIRED_INCLUDES ${ICUUC_DIR} ${ICUI18N_DIR})
     set(CMAKE_REQUIRED_LIBRARIES ${ICUUC} ${ICUI18N})
 else()
+    get_filename_component(ICUCORE_DIR ${ICUCORE} PATH)
+    set(CMAKE_REQUIRED_INCLUDES ${ICUCORE_DIR} PATH)
     set(CMAKE_REQUIRED_LIBRARIES ${ICUCORE})
 endif()
 
@@ -19,6 +24,7 @@ check_symbol_exists(
     "unicode/ucol.h"
     HAVE_SET_MAX_VARIABLE)
 
+unset(CMAKE_REQUIRED_INCLUDES)
 unset(CMAKE_REQUIRED_LIBRARIES)
 unset(CMAKE_REQUIRED_INCLUDES)
```

**Comment by seanshpark** [comment]
With above changes, this is the part of `CMakeError.log`
```
Determining if the ucol_setMaxVariable exist failed with the following output:
Change Dir: /home/maxwell/coreclr/bin/obj/Linux.arm.Debug/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/make "cmTryCompileExec42325184/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec42325184.dir/build.make CMakeFiles/cmTryCompileExec42325184.dir/build
make[1]: Entering directory `/home/maxwell/coreclr/bin/obj/Linux.arm.Debug/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/maxwell/coreclr/bin/obj/Linux.arm.Debug/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec42325184.dir/CheckSymbolExists.c.o
/home/maxwell/bin/llvm/bin/clang-3.8   -Wall -std=c11  -I/home/maxwell/zarm-rootfs-wily/usr/lib/arm-linux-gnueabihf    -target armv7-linux-gnueabihf -mthumb -mfpu=vfpv3 --sysroot=/home/maxwell/zarm-rootfs-wily -o CMakeFiles/cmTryCompileExec42325184.dir/CheckSymbolExists.c.o   -c /home/maxwell/coreclr/bin/obj/Linux.arm.Debug/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTryCompileExec42325184
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec42325184.dir/link.txt --verbose=1
/home/maxwell/bin/llvm/bin/clang-3.8   -Wall -std=c11        -target arm-linux-gnueabihf -B /home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf -L/home/maxwell/zarm-rootfs-wily/lib/arm-linux-gnueabihf --sysroot=/home/maxwell/zarm-rootfs-wily CMakeFiles/cmTryCompileExec42325184.dir/CheckSymbolExists.c.o  -o cmTryCompileExec42325184 -rdynamic -licuuc -licui18n 
/home/maxwell/bin/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-ld: warning: libicudata.so.55, needed by /home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so, not found (try using -rpath or -rpath-link)
/home/maxwell/bin/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-ld: warning: libdl.so.2, needed by /home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so, not found (try using -rpath or -rpath-link)
/home/maxwell/bin/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-ld: warning: libstdc++.so.6, needed by /home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so, not found (try using -rpath or -rpath-link)
/home/maxwell/bin/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-ld: warning: libm.so.6, needed by /home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so, not found (try using -rpath or -rpath-link)
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicui18n.so: undefined reference to `asin@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `log@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `operator delete(void*)@GLIBCXX_3.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `fmod@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicui18n.so: undefined reference to `sin@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `vtable for __cxxabiv1::__class_type_info@CXXABI_1.3'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `ceil@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicui18n.so: undefined reference to `acos@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicui18n.so: undefined reference to `tan@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `__cxa_call_unexpected@CXXABI_1.3'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `floor@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `__gxx_personality_v0@CXXABI_1.3'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicui18n.so: undefined reference to `atan@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `__cxa_end_cleanup@CXXABI_1.3'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicui18n.so: undefined reference to `atan2@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicui18n.so: undefined reference to `cos@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `pow@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `dlsym@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `dlclose@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `__dynamic_cast@CXXABI_1.3'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `vtable for __cxxabiv1::__si_class_type_info@CXXABI_1.3'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `icudt55_dat'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `vtable for __cxxabiv1::__vmi_class_type_info@CXXABI_1.3'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `__cxa_pure_virtual@CXXABI_1.3'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicui18n.so: undefined reference to `sincos@GLIBC_2.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `std::type_info::operator==(std::type_info const&) const@GLIBCXX_3.4'
/home/maxwell/zarm-rootfs-wily/usr/lib/gcc/arm-linux-gnueabihf/5.2.1/../../../arm-linux-gnueabihf/libicuuc.so: undefined reference to `dlopen@GLIBC_2.4'
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cmTryCompileExec42325184] Error 1
make[1]: Leaving directory `/home/maxwell/coreclr/bin/obj/Linux.arm.Debug/CMakeFiles/CMakeTmp'
make: *** [cmTryCompileExec42325184/fast] Error 2

File /home/maxwell/coreclr/bin/obj/Linux.arm.Debug/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <unicode/ucol.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef ucol_setMaxVariable
  return ((int*)(&ucol_setMaxVariable))[argc];
#else
  (void)argc;
  return 0;
#endif
}
```

**Comment by seanshpark** [comment]
@jasonwilliams200OK , I've tested with below change and works ok with both gcc 4.8 and 5.3, but don't seem nice. Do you have any better ways?
```
diff --git a/src/corefx/System.Globalization.Native/configure.cmake b/src/corefx/System.Globalization.Native/configure.cmake
index 138127e..1bb4be4 100644
--- a/src/corefx/System.Globalization.Native/configure.cmake
+++ b/src/corefx/System.Globalization.Native/configure.cmake
@@ -9,7 +9,7 @@ CHECK_CXX_SOURCE_COMPILES("
 " HAVE_UDAT_STANDALONE_SHORTER_WEEKDAYS)
 
 if(NOT CLR_CMAKE_PLATFORM_DARWIN)
-    set(CMAKE_REQUIRED_LIBRARIES ${ICUUC} ${ICUI18N})
+    set(CMAKE_REQUIRED_LIBRARIES ${ICUUC} ${ICUI18N} "icudata" "m" "stdc++" "dl")
 else()
     set(CMAKE_REQUIRED_LIBRARIES ${ICUCORE})
 endif()
```
I'm not sure about this change, how

**Comment by jasonwilliams200OK** [comment]
@seanshpark, I tested on Gentoo and your patch works. Correctness overweighs nice looks.. We can remove the double quotes however:

```cmake
set(CMAKE_REQUIRED_LIBRARIES ${ICUUC} ${ICUI18N} icudata m stdc++ dl)
```

Otherwise your patch is perfect!

**Comment by seanshpark** [comment]
@jasonwilliams200OK , thank you :) I'll prepare a PR

**Comment by seanshpark** [comment]
@jasonwilliams200OK , do you know anything about this? `freebsd` fails to build in CI.
```
17:17:12 /mnt/resource/j/workspace/dotnet_coreclr/master/checked_freebsd_prtest@
          2/src/corefx/System.Globalization.Native/collation.cpp:282:9:
          error: 'ucol_setVariableTop_53' is deprecated [-Werror,-Wdeprecated-declarations]
17:17:12         ucol_setVariableTop(pClonedCollator, ignoreSymbolsVariableTop, 1, pErr);
17:17:12         ^
17:17:12 /usr/local/include/unicode/urename.h:751:29: note: expanded from macro 'ucol_setVariableTop'
17:17:12 #define ucol_setVariableTop U_ICU_ENTRY_POINT_RENAME(ucol_setVariableTop)
```
or do we have to add `freebsd` also to `darwin` check?

**Comment by seanshpark** [comment]
I've updated the PR for testing
```
 if(NOT CLR_CMAKE_PLATFORM_DARWIN)
     set(CMAKE_REQUIRED_LIBRARIES ${ICUUC} ${ICUI18N})
+    if(NOT CLR_CMAKE_PLATFORM_FREEBSD)
+        set(CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES} icudata m stdc++ dl)
+    endif()
 else()
```

**Comment by seanshpark** [comment]
Above changes seems to work for `freebsd`, `CI` log is OK.
```
21:53:55 -- Looking for ucol_setMaxVariable
21:53:55 -- Looking for ucol_setMaxVariable - found
```

**Comment by jasonwilliams200OK** [comment]
@seanshpark, in this case can we instead add `icudata m stdc++ dl` for ARM? I mean white-listing, instead of black-list freebsd, then there would be others which CI is not covering ATM..

**Comment by seanshpark** [comment]
@jasonwilliams200OK , good idea, only for ARM :)

**Comment by seanshpark** [comment]
my `arm-linux-gnueabihf-ld` seems to be the problem, version is `2.25.0`.

while seeking for the reason, tried with this change in `cross/arm/toolchain.cmake` file,
```
-set(CROSS_LINK_FLAGS "${CROSS_LINK_FLAGS} --sysroot=${CROSS_ROOTFS}")
+set(CROSS_LINK_FLAGS "${CROSS_LINK_FLAGS} -Wl,--sysroot=${CROSS_ROOTFS}")
```
`ucol_setMaxVariable` finding is OK, but fails afterwards in
```
coreclr/src/ildasm/unixcoreclrloader/coreclrloader.cpp:32: undefined reference to
 `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
```

With the linker from ubuntu 15.10, version `2.25.1`, it works fine. I think I'll just go with using this without any `coreclr` changes.

@jasonwilliams200OK , thank you for the guide.
