### ISSUE TITLE
coreclr fails to build with glibc 2.26

### ISSUE THREAD

**Issue by omajid** [dotnet/coreclr#13009]
I cant build coreclr with a very recent version of glibc:

    builddir/build/BUILD/dotnet-sdk-2.0.0-preview2-006497/src/coreclr/src/pal/src/include/pal/context.h(162,66): error G6247A3BF: no member named 'padding' in '_libc_fpstate' [/builddir/build/BUILD/dotnet-sdk-2.0.0-preview2-006497/targets/repository.proj]
          return reinterpret_cast<_fpx_sw_bytes *>(&FPREG_Fpstate(uc)->padding[12]);
                                                    ~~~~~~~~~~~~~~~~~  ^
      1 error generated.

See https://sourceware.org/bugzilla/show_bug.cgi?id=21457 and https://sourceware.org/glibc/wiki/Release/2.26#Removal_of_.27struct_ucontext.27

**Comment by janvorli** [comment]
@omajid thank you for pointing it out. What distro has such a glibc? I'd like to fix it.

**Comment by omajid** [comment]
No problem! I was doing this build today on current Fedora rawhide - basically the in-development version of Fedora that will become Fedora 27. [This page](https://fedoraproject.org/wiki/Releases/Rawhide#Using_Rawhide) has some steps on how to install Rawhide.

**Comment by omajid** [comment]
I can reproduce this using the in-development version of F27: http://download.fedoraproject.org/pub/fedora/linux/development/27/Workstation/x86_64/iso/

This makes coreclr build in Fedora 27: https://gist.github.com/omajid/436df7f7d04956b9b7fd416524cfe926. I dont know of a way to conditionalize `padding`/`__glibc_reserved1` based on a specific version of glibc, yet.

**Comment by janvorli** [comment]
@omajid thank you for bringing this back to my attention. As for conditionalizing, we can easily use the build time detection of the __glibc_reserved1 field presence in the structure.

**Comment by omajid** [comment]
Thanks for the tip, @janvorli !
