### ISSUE TITLE
[Crossgen/Linux/x86] [Ubuntu 16.04.3] Build failure: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

### ISSUE THREAD

**Issue by 4creators** [dotnet/coreclr#14278]
Build on WSL Ubuntu 16.04 with clang 3.9.1 for x86/Release target fails:

```
Generating native image for System.Private.CoreLib.
/mnt/e/src/ms/dotnet/coreclr-lnx/bin/Product/Linux.x86.Release/crossgen /Platform_Assemblies_Paths /mnt/e/src/ms/dotnet/coreclr-lnx/bin/Product/Linux.x86.Release/IL  /out /mnt/e/src/ms/dotnet/coreclr-lnx/bin/Product/Linux.x86.Release/System.Private.CoreLib.dll /mnt/e/src/ms/dotnet/coreclr-lnx/bin/Product/Linux.x86.Release/IL/System.Private.CoreLib.dll
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Could not load file or assembly '/mnt/e/src/ms/dotnet/coreclr-lnx/bin/Product/Linux.x86.Release/IL/System.Private.CoreLib.dll'. An attempt was made to load a program with an incorrect format.
 (Exception from HRESULT: 0x8007000B)
Error: compilation failed for "/mnt/e/src/ms/dotnet/coreclr-lnx/bin/Product/Linux.x86.Release/IL/System.Private.CoreLib.dll" (0x8007000b)
Failed to generate native image for System.Private.CoreLib.
```
Build for x64/Release target succeeds.

repo commit: c90a41bb6b9b5c5cc7f8f29a9d06aa2f9d0e51fd

**Comment by janvorli** [comment]
@4creators I don't think WSL allows running 32 bit stuff. Also, what was the build.sh command line you've used for building the stuff?

**Comment by 4creators** [comment]
@janvorli  ./build.sh -x86 -Release

**Comment by 4creators** [comment]
> I don't think WSL allows running 32 bit stuff
@janvorli 
Do you think that it should be possible to use crossgen x64 build for compiling S.P.CoreLib (I assume that yes but would like to have confirmation).
Are there any other tools (tests) which would require 64 bit tools to get them compiled?

If you think it's doable I will try to create PR to support WSL (prefer it in comparison to VMs).

**Comment by 4creators** [comment]
@janvorli unfortunately I am hitting the very same error on fresh Ubuntu 16.04.3 VM running on Hyper-V 

Build command: ./build.sh -x86 -Release -skiptests -nopgooptimize
```
Generating native image for System.Private.CoreLib.
/home/developer/src/coreclr/bin/Product/Linux.x86.Release/crossgen /Platform_Assemblies_Paths /home/developer/src/coreclr/bin/Product/Linux.x86.Release/IL  /out /home/developer/src/coreclr/bin/Product/Linux.x86.Release/System.Private.CoreLib.dll /home/developer/src/coreclr/bin/Product/Linux.x86.Release/IL/System.Private.CoreLib.dll
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Could not load file or assembly '/home/developer/src/coreclr/bin/Product/Linux.x86.Release/IL/System.Private.CoreLib.dll'. An attempt was made to load a program with an incorrect format.
 (Exception from HRESULT: 0x8007000B)
Error: compilation failed for "/home/developer/src/coreclr/bin/Product/Linux.x86.Release/IL/System.Private.CoreLib.dll" (0x8007000b)
Failed to generate native image for System.Private.CoreLib.

```

**Comment by janvorli** [comment]
@4creators I am sorry I have not realized that you were not passing the "cross" option to the build before. You cannot just build for x86 on x64, cross build is required. So you need to generate rootfs using the `./cross/build-rootfs.sh x86` and then build with the `cross` option (`./build.sh cross x86`).

**Comment by RussKeldorph** [comment]
Feel free to re-open if the resolution is not satisfactory.
