### ISSUE TITLE
coreclr fails to build with glibc 2.30 due to sys/sysctl.h deprecation

### ISSUE THREAD

**Issue by omajid** [dotnet/coreclr#27008]
Building coreclr on Fedora 32, with glibc 2.30 gives me:

```
In file included from /coreclr/src/pal/src/misc/sysinfo.cpp:32:
/usr/include/sys/sysctl.h:21:2: error: "The <sys/sysctl.h> header is deprecated and will be removed." [-Werror,-W#warnings]
#warning "The <sys/sysctl.h> header is deprecated and will be removed."
 ^
1 error generated.
make[2]: *** [src/pal/src/CMakeFiles/coreclrpal.dir/build.make:687: src/pal/src/CMakeFiles/coreclrpal.dir/misc/sysinfo.cpp.o] Error 1
```

This is a change in glibc 2.30. See http://patches-tcwg.linaro.org/patch/19443/ for their discussion. This is affecting other projects too, for example https://bugs.launchpad.net/ubuntu/+source/squid/+bug/1843325

**Comment by omajid** [comment]
cc @tmds

**Comment by janvorli** [comment]
This can be fixed by making check for HAVE_SYSINFO before the HAVE_SYSCONF so that we don't try to include the header if the HAVE_SYSINFO is 1. The code in the file below has this order of checks too, so it would be correct.

**Comment by omajid** [comment]
@janvorli, thanks! I am a little confused about `HAVE_SYSINFO`/`HAVE_SYSCONF`... the code looks like it uses `HAVE_SYSCONF`/`HAVE_SYSCTL` pairs. I opened a PR here: https://github.com/dotnet/coreclr/pull/27048. Please let me know if I messed something up.
