### ISSUE TITLE
CoreCLR does not build on mac os x version 10.12.4

### ISSUE THREAD

**Issue by JohnGorter** [dotnet/coreclr#9826]
Hope someone can help me. The build is too fragile on my machine.. I am getting error-after-error.

Now I am stuck at 6% where the following output is shown:
[  6%] Linking CXX static library libcee_crossgen.a
[  6%] Built target cee_crossgen
make: *** [all] Error 2
Failed to build CoreCLR component.

A few lines previous I saw a couple of errors:
[  3%] Building CXX object src/vm/crossgen/CMakeFiles/cee_crossgen.dir/__/binder.cpp.o
/Users/johngorter/desktop/core3/coreclr/src/pal/src/exception/seh.cpp:56:12: error:
      explicit specialization of non-template struct 'remove_reference'
    struct remove_reference<T&>
           ^               ~~~~
/Users/johngorter/desktop/core3/coreclr/src/pal/src/exception/seh.cpp:62:12: error:
      explicit specialization of non-template struct 'remove_reference'
    struct remove_reference<T&&>

I am trying to build the coreclr on a mac with a fresh install of XCODE.
What am I doing wrong? Can anyone help?

TIA,
John.

**Comment by janvorli** [comment]
@JohnGorter my quick guess is that something has changed in the latest xcode headers that causes the remove_reference to be defined to something else that collides with our definition. Let me try to upgrade the OSX / xcode on my Mac and look into it.

**Comment by janvorli** [comment]
@JohnGorter I have tried to search for updates on my Mac and it didn't find any newer OSX than 10.12.3. Maybe I just need to wait for it to become available. I haven't used that machine for a while and it upgraded to 10.12.3 just today.

As for the xcode, what version do you have? I have version 8.2.1 and again, the app store doesn't offer me update to anything newer.
```xcodebuild -version
Xcode 8.2.1
Build version 8C1002
```

**Comment by shahid-pk** [comment]
OSX 10.12.4 is in beta and is available for developers i think

**Comment by JohnGorter** [comment]
thanks for the quick reply... yes it is a beta version of Sierra..
and i am on xcode version 8.2.1, Build version 8C1002.

**Comment by janvorli** [comment]
@JohnGorter then I'd prefer waiting for it to become final, the issue can be related to the fact it is in beta.
But we can do a bit more diagnostic if you want. We can generate preprocessed file for the seh.cpp and see where the problem comes from. Assuming you are building for debug, could you please try the following?:
* cd bin/obj/OSX.x64.Debug/src/pal/src
* make exception/seh.cpp.i

Then please share the generated seh.cpp.i with me. It should be obvious where the problem stems from.

**Comment by JohnGorter** [comment]
[seh.cpp.i.zip](https://github.com/dotnet/coreclr/files/806312/seh.cpp.i.zip)

**Comment by JohnGorter** [comment]
Please share your thoughts when you went through the file, thanks!

**Comment by janvorli** [comment]
The issue stems from the /usr/local/Cellar/llvm/3.9.1/bin/../include/c++/v1/type_traits that contains the definition of the remove_reference and that is included during the compilation of the seh.cpp.
When I look at the seh.cpp.i at my machine, the `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/math.h` is included instead, so it looks like your local install of the llvm is conflicting with the headers from the macos. In my build, all headers are consistently coming from `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk` subfolders while in your build, some come from `usr/local/Cellar/llvm/3.9.1/bin/../include` and some from the `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk` subfolders, so it looks like some misconfiguration of include paths on your system.

**Comment by JohnGorter** [comment]
The makefile in the bin/obj/OSX.x64.Debug/src/pal/src directory is defined as:
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.2/bin/cmake

shouldnt that also be a reference to the xcode version?


John.

**Comment by janvorli** [comment]
I don't think xcode contains cmake. Btw, these makefiles are generated by the cmake itself.

**Comment by JohnGorter** [comment]
Do you know where the libraries are determined? does this issue relate to: http://stackoverflow.com/questions/16277902/cmake-find-library-returns-wrong-path

**Comment by janvorli** [comment]
@JohnGorter I don't think it is related to the stackoverflow issue. The problem here are not libraries, but the standard C/C++ headers.
Could you please run `env` command from the command prompt and see of there are any env variables set pointing somewhere to the `/usr/local/Cellar/llvm`?

**Comment by JohnGorter** [comment]
TERM_PROGRAM=iTerm.app
TERM=xterm-256color
SHELL=/bin/bash
TMPDIR=/var/folders/mj/163htgjs78z18dr4lkh5n3tm0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.Z79RoRpQk7/Render
TERM_PROGRAM_VERSION=3.0.14
OLDPWD=/Users/johngorter/Desktop/core2
TERM_SESSION_ID=w0t0p0:B0A7F4D9-A42E-46C5-9888-0197849A2C94
USER=johngorter
COMMAND_MODE=unix2003
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.wiiqi8nmlL/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x5
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/usr/local/git/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/JohnGorter/Library/Android/sdk/platform-tools:/Users/JohnGorter/Library/Android/sdk/build-tools/24.0.1
PWD=/Users/johngorter/Desktop/core2/coreclr
LANG=nl_NL.UTF-8
ITERM_PROFILE=Default
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/johngorter
COLORFGBG=7;0
ITERM_SESSION_ID=w0t0p0:B0A7F4D9-A42E-46C5-9888-0197849A2C94
PYTHONPATH=:/Users/johngorter/Downloads/python-sdk
LOGNAME=johngorter
SECURITYSESSIONID=186a7
_=/usr/bin/env
Johns-Mac:coreclr johngorter$ env
TERM_PROGRAM=iTerm.app
TERM=xterm-256color
SHELL=/bin/bash
TMPDIR=/var/folders/mj/163htgjs78z18dr4lkh5n3tm0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.Z79RoRpQk7/Render
TERM_PROGRAM_VERSION=3.0.14
OLDPWD=/Users/johngorter/Desktop/core2
TERM_SESSION_ID=w0t0p0:B0A7F4D9-A42E-46C5-9888-0197849A2C94
USER=johngorter
COMMAND_MODE=unix2003
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.wiiqi8nmlL/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x5
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/usr/local/git/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/JohnGorter/Library/Android/sdk/platform-tools:/Users/JohnGorter/Library/Android/sdk/build-tools/24.0.1
PWD=/Users/johngorter/Desktop/core2/coreclr
LANG=nl_NL.UTF-8
ITERM_PROFILE=Default
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/johngorter
COLORFGBG=7;0
ITERM_SESSION_ID=w0t0p0:B0A7F4D9-A42E-46C5-9888-0197849A2C94
PYTHONPATH=:/Users/johngorter/Downloads/python-sdk
LOGNAME=johngorter
SECURITYSESSIONID=186a7
_=/usr/bin/env

**Comment by janvorli** [comment]
Hmm, nothing there. So one more idea on what to try. Can you please run similar command to the one you have run before to get the preprocessed file, but with a little change (added `-n` option to make) and get me the output of the command?
* cd bin/obj/OSX.x64.Debug/src/pal/src
* make -n exception/seh.cpp.i
It will show the exact command line that is being used to compile the seh.cpp, including the full path to the clang and all the include paths.

**Comment by JohnGorter** [comment]
Johns-Mac:coreclr johngorter$ cd bin/obj/OSX.x64.Debug/src/pal/src
Johns-Mac:src johngorter$ make -n exception/seh.cpp.i
cd /Users/johngorter/desktop/core2/coreclr/bin/obj/OSX.x64.Debug && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/pal/src/CMakeFiles/coreclrpal.dir/build.make src/pal/src/CMakeFiles/coreclrpal.dir/exception/seh.cpp.i
/usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_echo_color --switch= --green "Preprocessing CXX source to CMakeFiles/coreclrpal.dir/exception/seh.cpp.i"
cd /Users/johngorter/desktop/core2/coreclr/bin/obj/OSX.x64.Debug/src/pal/src && /usr/local/bin/clang++  -DAMD64 -DBIT64=1 -DBUILDENV_CHECKED=1 -DCORECLR=1 -DDEBUG -DDISABLE_CONTRACTS -DFEATURE_PAL=1 -DLP64COMPATIBLE=1 -DPIC=1 -DPLATFORM_UNIX=1 -DURTBLDENV_FRIENDLY=Checked -DXSTATE_SUPPORTED -D_AMD64_ -D_DBG -D_DEBUG -D_FILE_OFFSET_BITS=64 -D_TARGET_MAC64 -D_WIN64 -D_WIN64=1 -I/Users/johngorter/desktop/core2/coreclr/bin/obj/OSX.x64.Debug/src/pal/src -I/Users/johngorter/desktop/core2/coreclr/src/pal/src -I/Users/johngorter/desktop/core2/coreclr/src/pal/inc -I/Users/johngorter/desktop/core2/coreclr/src/pal/../inc -isystem /usr/local/include -I/Users/johngorter/desktop/core2/coreclr/src/pal/src/include  -Wall -Wno-null-conversion -std=c++11 -g -O0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk   -fno-omit-frame-pointer -fms-extensions -fwrapv -fstack-protector -ferror-limit=4096 -Werror -Wno-unused-private-field -Wno-unused-variable -Wno-microsoft -Wno-tautological-compare -Wno-constant-logical-operand -Wno-unknown-warning-option -Wno-invalid-offsetof -Wno-incompatible-ms-struct -fsigned-char -fexceptions -fPIC -E /Users/johngorter/desktop/core2/coreclr/src/pal/src/exception/seh.cpp > CMakeFiles/coreclrpal.dir/exception/seh.cpp.i

**Comment by janvorli** [comment]
Ok, I think the issue is related to the fact that you are not building it with clang from the xcode, but rather some other clang++ installed in /usr/local/bin/. On my OSX, the clang++ is in /usr/bin.
Can you please run 
`which clang++`
and
`clang++ --version`?

**Comment by JohnGorter** [comment]
you are correct:
Johns-Mac:src johngorter$ which clang++
/usr/local/bin/clang++
Johns-Mac:src johngorter$ /usr/local/bin/clang++ --version
clang version 3.9.1 (tags/RELEASE_391/final)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /usr/local/bin

**Comment by janvorli** [comment]
Do you have the additional clang installed intentionally for some reason?
Anyways, it seems we can set the PATH before the build to exclude the /usr/local/bin, which could fix the issue for you.
Can you please try the following steps from the root of the cloned coreclr tree?
* rm -r bin
* PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/usr/local/git/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/JohnGorter/Library/Android/sdk/platform-tools:/Users/JohnGorter/Library/Android/sdk/build-tools/24.0.1
* ./build.sh cmakeargs DSKIP_LLDBPLUGIN=1

**Comment by janvorli** [comment]
Sigh. I haven't realized that cmake has a link in /usr/local/bin. 
But from one of your previous comments, I can see that the cmake is actually in /usr/local/Cellar/cmake/3.7.2/bin and so probably there is just a link in the /usr/local/bin.
Could you please try to set the PATH rather like this to see if it helps?:
`PATH=/usr/local/Cellar/cmake/3.7.2/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/usr/local/git/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/JohnGorter/Library/Android/sdk/platform-tools:/Users/JohnGorter/Library/Android/sdk/build-tools/24.0.1`

**Comment by JohnGorter** [comment]
Just for my understanding: how come two clang++ installs end up in breaking the build. Was the default clang++ compiler using the wrong configuration?

**Comment by janvorli** [comment]
Frankly I don't know. We have never tried to build coreclr on OSX using other clang than the one from xcode. And clang 3.9.1 on Linux builds coreclr just fine. So I guess that due to the intermix of headers from OSX and the new clang, the type_traits file gets included and provides definitions for the same stuff as we define in seh.cpp. The reason why we define these ourselves is described in the comment above the block with the failing line.
So another fix for you might be to comment out the whole namespace std block (lines 47..72). Maybe the build would succeed too, but maybe you'll get other errors elsewhere due to the same reason.

**Comment by jeffschwMSFT** [comment]
The minimal supported OSX version is now 10.13.
