### ISSUE TITLE
[x64/Windows] Failures in checked outerloop job

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#17744]
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/checked_windows_nt/9461/consoleText

Looks like these started failing after #17680.

@sywhang 

```
D:\j\workspace\checked_windo---14fb495b\bin\tests\Windows_NT.x64.Checked\TestWrappers\GC.API\GC.API.XUnitWrapper.cs(1017): error : GC_API._GCHandle_HandleCopy_HandleCopy_._GCHandle_HandleCopy_HandleCopy_cmd [FAIL] [D:\j\workspace\checked_windo---14fb495b\tests\runtest.proj]
        
  Return code:      1
  Raw output file:      D:\j\workspace\checked_windo---14fb495b\bin\tests\Windows_NT.x64.Checked\Reports\GC.API\GCHandle\HandleCopy\HandleCopy.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\checked_windo---14fb495b\tests\..\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" HandleCopy.exe 
        Allocating a Weak handle to object..
        Test for Copy of GCHandle failed!
        Expected: 100
        Actual: 1
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\checked_windo---14fb495b\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
  > D:\j\workspace\checked_windo---14fb495b\bin\tests\Windows_NT.x64.Checked\GC\API\GCHandle\HandleCopy\HandleCopy.cmd
  
        Expected: True
        Actual:   False
D:\j\workspace\checked_windo---14fb495b\bin\tests\Windows_NT.x64.Checked\TestWrappers\GC.API\GC.API.XUnitWrapper.cs(1017,0): at GC_API._GCHandle_HandleCopy_HandleCopy_._GCHandle_HandleCopy_HandleCopy_cmd()
```

```
D:\j\workspace\checked_windo---14fb495b\bin\tests\Windows_NT.x64.Checked\TestWrappers\GC.Features\GC.Features.XUnitWrapper.cs(247): error : GC_Features._Finalizer_finalizeother_finalizearraysleep_finalizearraysleep_._Finalizer_finalizeother_finalizearraysleep_finalizearraysleep_cmd [FAIL] [D:\j\workspace\checked_windo---14fb495b\tests\runtest.proj]
        
  
  Return code:      1
  Raw output file:      D:\j\workspace\checked_windo---14fb495b\bin\tests\Windows_NT.x64.Checked\Reports\GC.Features\Finalizer\finalizeother\finalizearraysleep\finalizearraysleep.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\checked_windo---14fb495b\tests\..\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" finalizearraysleep.exe 
        Test for Finalize() for array of objects passed!
        Expected: 100
        Actual: 0
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\checked_windo---14fb495b\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
  > D:\j\workspace\checked_windo---14fb495b\bin\tests\Windows_NT.x64.Checked\GC\Features\Finalizer\finalizeother\finalizearraysleep\finalizearraysleep.cmd
  
        Expected: True
        Actual:   False
          D:\j\workspace\checked_windo---14fb495b\bin\tests\Windows_NT.x64.Checked\TestWrappers\GC.Features\GC.Features.XUnitWrapper.cs(247,0): at GC_Features._Finalizer_finalizeother_finalizearraysleep_finalizearraysleep_._Finalizer_finalizeother_finalizearraysleep_finalizearraysleep_cmd()
```

**Comment by erozenfeld** [comment]
A lot of other jobs in ci are failing in the same way. Some additionally have this failure:

```
D:\j\workspace\x64_checked_w---a16971a7\bin\tests\Windows_NT.x64.Checked\TestWrappers\GC.Scenarios\GC.Scenarios.XUnitWrapper.cs(1787): error : GC_Scenarios._FinalNStruct_nstructtun_nstructtun_._FinalNStruct_nstructtun_nstructtun_cmd [FAIL] [D:\j\workspace\x64_checked_w---a16971a7\tests\runtest.proj]
        
  
  Return code:      1
  Raw output file:      D:\j\workspace\x64_checked_w---a16971a7\bin\tests\Windows_NT.x64.Checked\Reports\GC.Scenarios\FinalNStruct\nstructtun\nstructtun.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\x64_checked_w---a16971a7\tests\..\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" nstructtun.exe 
        Test should return with ExitCode 100 ...
        iRep = 10000
        10000 NStruct Objects were deleted and 9999 finalized.
        Test Failed
        Expected: 100
        Actual: 1
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\x64_checked_w---a16971a7\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
  > D:\j\workspace\x64_checked_w---a16971a7\bin\tests\Windows_NT.x64.Checked\GC\Scenarios\FinalNStruct\nstructtun\nstructtun.cmd
  
        Expected: True
        Actual:   False
          D:\j\workspace\x64_checked_w---a16971a7\bin\tests\Windows_NT.x64.Checked\TestWrappers\GC.Scenarios\GC.Scenarios.XUnitWrapper.cs(1787,0): at GC_Scenarios._FinalNStruct_nstructtun_nstructtun_._FinalNStruct_nstructtun_nstructtun_cmd()
```

E.g., https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_minopts/494/consoleText

**Comment by BruceForstall** [comment]
This happens on all platforms.

**Comment by sywhang** [comment]
https://github.com/dotnet/coreclr/pull/17766 is out to fix these failures.
