### PR TITLE
Fix compilation errors on tests.

### LINKED ISSUE #3531: UIntPtrGetHashCode.csproj and IntPtrGetHashCode.csproj have build problems
The build error were introduced in https://github.com/dotnet/coreclr/pull/3511/files

intptrgethashcode.cs(117,17): error CS0103: The name 'retVal' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\intptr\IntPtrGetHashCode.csproj]
intptrgethashcode.cs(125,24): error CS0103: The name 'retVal' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\intptr\IntPtrGetHashCode.csproj]
intptrgethashcode.cs(129,52): error CS0103: The name 'id' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\intptr\IntPtrGetHashCode.csproj]
intptrgethashcode.cs(129,140): error CS0103: The name 'i' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\intptr\IntPtrGetHashCode.csproj]
intptrgethashcode.cs(130,17): error CS0103: The name 'retVal' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\intptr\IntPtrGetHashCode.csproj]
intptrgethashcode.cs(136,13): error CS0103: The name 'retVal' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\intptr\IntPtrGetHashCode.csproj]
intptrgethashcode.cs(138,16): error CS0103: The name 'retVal' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\intptr\IntPtrGetHashCode.csproj]
uintptrgethashcode.cs(169,48): error CS1503: Argument 1: cannot convert from 'long' to 'uint' [E:\git\coreclr\tests\src\CoreMangLib\cti\system\uintptr\UIntPtrGetHashCode.csproj]
uintptrgethashcode.cs(170,48): error CS1503: Argument 1: cannot convert from 'long' to 'uint' [E:\git\coreclr\tests\src\CoreMangLib\cti\system\uintptr\UIntPtrGetHashCode.csproj]
uintptrgethashcode.cs(174,17): error CS0103: The name 'retVal' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\uintptr\UIntPtrGetHashCode.csproj]
uintptrgethashcode.cs(182,24): error CS0103: The name 'retVal' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\uintptr\UIntPtrGetHashCode.csproj]
uintptrgethashcode.cs(186,52): error CS0103: The name 'id' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\uintptr\UIntPtrGetHashCode.csproj]
uintptrgethashcode.cs(186,140): error CS0103: The name 'i' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\uintptr\UIntPtrGetHashCode.csproj]
uintptrgethashcode.cs(187,17): error CS0103: The name 'retVal' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\uintptr\UIntPtrGetHashCode.csproj]
uintptrgethashcode.cs(193,13): error CS0103: The name 'retVal' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\uintptr\UIntPtrGetHashCode.csproj]
uintptrgethashcode.cs(195,16): error CS0103: The name 'retVal' does not exist in the current context [E:\git\coreclr\tests\src\CoreMangLib\cti\system\uintptr\UIntPtrGetHashCode.csproj]

### PR DESCRIPTION
**Pull request by vcsjones**
Fix #3531

### CODE REVIEW

**Comment by vcsjones** [comment]
Seems like the Windows x86 build timed out.

**Comment by ramarag** [comment]
@dotnet-bot  test Windows_NT x86 Debug Build
