### PR TITLE
Add support for building under glibc 2.26

### LINKED ISSUE #13009: coreclr fails to build with glibc 2.26
I cant build coreclr with a very recent version of glibc:

    builddir/build/BUILD/dotnet-sdk-2.0.0-preview2-006497/src/coreclr/src/pal/src/include/pal/context.h(162,66): error G6247A3BF: no member named 'padding' in '_libc_fpstate' [/builddir/build/BUILD/dotnet-sdk-2.0.0-preview2-006497/targets/repository.proj]
          return reinterpret_cast<_fpx_sw_bytes *>(&FPREG_Fpstate(uc)->padding[12]);
                                                    ~~~~~~~~~~~~~~~~~  ^
      1 error generated.

See https://sourceware.org/bugzilla/show_bug.cgi?id=21457 and https://sourceware.org/glibc/wiki/Release/2.26#Removal_of_.27struct_ucontext.27

### PR DESCRIPTION
**Pull request by omajid**
glibc 2.26 renames a number of identifiers so they are reserved under POSIX. Specifically, `padding` becomes `__glibc_reserved1`. Add a configure test for it and use the appropriate field name.

See https://sourceware.org/bugzilla/show_bug.cgi?id=21457 for more information.

Resolves #13009

### CODE REVIEW

File: src/pal/src/include/pal/context.h [hunk 1]
```diff
@@ -21,6 +21,8 @@ Module Name:
 #ifndef _PAL_CONTEXT_H_
 #define _PAL_CONTEXT_H_
 
+#include "config.h"
```
Comment (janvorli) [inline src/pal/src/include/pal/context.h]: A nit - this is not needed. The config.h is included in palinternal.h that needs to be always included before this header. We already use a couple of HAVE_xxxx macros in this file.

Comment (omajid) [reply src/pal/src/include/pal/context.h]: Oops. Fixed now.

**Comment by dagood** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test

Failure was regexdna which is [known flaky](https://github.com/dotnet/coreclr/issues/13779).
