### PR TITLE
Fix Performance Runs

### PR DESCRIPTION
**Pull request by DrewScoggins**
This fixes the performance runs to work with the new 2.0 build tools
package that we just took.

### CODE REVIEW

**Comment by DrewScoggins** [comment]
@gkhanna79 @wtgodbe Once the tests go green here we can merge this.

**Comment by DrewScoggins** [comment]
@swaroop-sridhar The ILLink tests are failing.  Can you please take a look at what is wrong with them?

**Comment by gkhanna79** [comment]
I see the following failure:

`Startup.cs(127,25): error CS1061: 'MicrosoftAccountOptions' does not contain a definition for 'DisplayName' and no extension method 'DisplayName' accepting a first argument of type 'MicrosoftAccountOptions' could be found (are you missing a using directive or an assembly reference?) [D:\j\workspace\perf_perflab_---c84e0eaf\sandbox\JitBench\src\MusicStore\MusicStore.csproj]`

Was this clean for your locally @DrewScoggins ?

CC @wtgodbe @weshaggard

**Comment by weshaggard** [comment]
@DrewScoggins I'm happy to help with this but I cannot figure out how to test these changes locally. What is the correct command to setup the perf runs?

**Comment by DrewScoggins** [comment]
I just ran through the microbenchmarks and did not run the ILLink tests.  It looks like however, that the failure is in the JitBench repo as we are seeing the same behavior in our JitBenchStart runs that happen from the perf-infra repo.  So I do not believe that this is related to the move to 2.0.

I think the right course of action at this point is to move this ILLink off of the inner loop performance correctness run, as it can be more flaky.  We will move it on to one of our other per commit runs, but not here.

**Comment by gkhanna79** [comment]
@DrewScoggins @valenis Are you still looking into the Perf infra bringup?

**Comment by DrewScoggins** [comment]
Yes, I should have this issue fixed in about 30 minutes.

**Comment by gkhanna79** [comment]
CC @russellhadley @swaroop-sridhar 

@swaroop-sridhar Can you please file an issue against yourself to track re-enabling MusicStore for 2.0?

**Comment by sbomer** [comment]
@swaroop-sridhar this should be fixed by https://github.com/aspnet/JitBench/pull/49.

**Comment by gkhanna79** [comment]
@DrewScoggins @swaroop-sridhar CI is green! Can we merge this?

**Comment by DrewScoggins** [comment]
Yup

**Comment by gkhanna79** [comment]
Thanks for merging this. Can you please prepare a port of this for release/2.0.0 branch and email shiproom about it so that we get it there as well?
