### PR TITLE
Guarded devirtualization foundations

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Exploratory changes to enable guarded devirtualization. See the design doc for motivation and discussion.

This series of changes mainly introduces the ability to do the proper transformation. The heuristics for when to transform and what to guess for are quite crude, but serve, for now, as a good stress test. The middle part of the commit stream includes some experimental runtime changes (thanks to @davidwrighton) that would support better decision making, but those have been undone by later commits. They will return at some point.

I will likely split this up into a series of smaller PRs once I've thought though some of the open issues and figured out how I really want to refactor things. But I want to expose this now for some broader testing and early feedback.

[Edit: am now going to just submit this one PR, but the transformation will be disabled by default for now].

cc @dotnet/jit-contrib (feel free to comment, but don't feel obligated)

Current crude heuristic has a pretty sizeable impact on code size:
```
PMI Diffs for System.Private.CoreLib.dll, framework assemblies for x64 default jit
Summary:
(Lower is better)
Total bytes of diff: 1923401 (5.15% of base)
    diff is a regression.
Top file regressions by size (bytes):
      436212 : Microsoft.CodeAnalysis.VisualBasic.dasm (7.80% of base)
      339130 : System.Private.Xml.dasm (9.37% of base)
      330916 : Microsoft.CodeAnalysis.CSharp.dasm (7.60% of base)
      105677 : System.Data.Common.dasm (8.07% of base)
       97797 : System.Private.DataContractSerialization.dasm (12.75% of base)
119 total files with size differences (0 improved, 119 regressed), 10 unchanged.
Top method regressions by size (bytes):
       19555 (150.86% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - BoundTreeVisitor`2:VisitInternal(ref,struct):long:this
        8076 (96.52% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - BoundTreeVisitor`2:VisitInternal(ref,double):long:this
        7747 (111.55% of base) : System.Private.Xml.dasm - XmlSerializationWriterCodeGen:WriteElements(ref,ref,ref,ref,ref,ref,bool,bool):this
        7483 (51.50% of base) : System.Data.Common.dasm - XmlTreeGen:HandleTable(ref,ref,ref,bool):ref:this
        7277 (111.64% of base) : Microsoft.CodeAnalysis.CSharp.dasm - BoundTreeVisitor`2:VisitInternal(ref,struct):long:this
Top method improvements by size (bytes):
        -790 (-4.49% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - Binder:ReportOverloadResolutionFailureForASingleCandidate(ref,ref,int,byref,struct,struct,bool,bool,bool,bool,ref,ref,bool,ref,ref):this
        -155 (-16.47% of base) : Microsoft.CodeAnalysis.CSharp.dasm - IteratorStateMachine:.ctor(ref,ref,ref,int,bool,ref):this
        -132 (-10.56% of base) : System.Net.Requests.dasm - FtpWebRequest:FinishRequestStage(int):int:this
         -82 (-8.35% of base) : System.Net.Http.dasm - WinHttpRequestCallback:OnRequestSendingRequest(ref)
         -67 (-32.84% of base) : System.Collections.NonGeneric.dasm - ReadOnlyCollectionBase:get_Count():int:this
Top method regressions by size (percentage):
         220 (1,047.62% of base) : System.Private.CoreLib.dasm - Progress`1:System.IProgress<T>.Report(struct):this
         158 (831.58% of base) : Newtonsoft.Json.dasm - JToken:System.Dynamic.IDynamicMetaObjectProvider.GetMetaObject(ref):ref:this
         189 (756.00% of base) : System.Private.DataContractSerialization.dasm - XmlWriterDelegator:WriteDecimal(struct):this
         144 (600.00% of base) : System.Net.Requests.dasm - HttpWebResponse:Close():this
         125 (568.18% of base) : System.Private.Xml.dasm - XmlBaseConverter:ToString(ref):ref:this
Top method improvements by size (percentage):
         -10 (-50.00% of base) : System.Private.CoreLib.dasm - CultureInfo:ToString():ref:this (2 base, 1 diff methods)
         -18 (-50.00% of base) : System.Private.CoreLib.dasm - RuntimeAssembly:get_ManifestModule():ref:this (2 base, 1 diff methods)
         -20 (-50.00% of base) : System.Private.CoreLib.dasm - FileStream:get_IsClosed():bool:this (2 base, 1 diff methods)
         -24 (-50.00% of base) : System.Private.CoreLib.dasm - Hashtable:Add(ref,ref):this (2 base, 1 diff methods)
          -9 (-50.00% of base) : System.Runtime.Extensions.dasm - ArrayList:get_Count():int:this (2 base, 1 diff methods)
27393 total methods with size differences (129 improved, 27264 regressed), 163883 unchanged.
```

### CODE REVIEW

File: Documentation/design-docs/GuardedDevirtualization.md [hunk 1]
```diff
@@ -0,0 +1,522 @@
...
+
+The graph below shows the measured results. To makes sure we're not overly impacted
+by residual VSD state we use a fresh call site for each value of p. The solid
+orange line is the current cost. The dashed orange line is the corresponding cost
+for a virtual call with the same value of p. The solid blue line is the cost with
+an up-front guarded test. As noted there is some slowdown when the jit always
+guesses the wrong class, but the break-even point (not shown) is at a relatively
+small probability of a correct guess.
+
+![two classes interface devirt](TwoClassesInterface.JPG)
```
Comment (benaadams) [inline Documentation/design-docs/GuardedDevirtualization.md]: Small jpg `TwoClassesInterface.JPG` => `TwoClassesInterface.jpg`

**Comment by benaadams** [comment]
Beautiful! ❤️ 

Resolves: https://github.com/dotnet/coreclr/issues/8819 and then some 😄

File: Documentation/design-docs/GuardedDevirtualization.md (hunk 1 above)
Comment (benaadams) [reply Documentation/design-docs/GuardedDevirtualization.md]: Or change the file name to have a CAPs extension

**Comment by benaadams** [comment]
Great analysis in the design doc. 

One area that may get significant benefits from guarded devirtualization of Interface Calls (over something like Linq) is dependency injection (and ASP.NET Core due to this).

Generally types are commonly defined via interface; so they can be easily adapted for the app and for ease of testing; however per app the concrete type to  resolve is generally defined at start up and baked to be only one type for the application's lifetime so monomorphic dispatch becomes very common. 

The impact would likely improve as you move further up the ASP.NET Core stack (into MVC and user code) as layers of interfaces compound on each other through specific call sites.

**Comment by benaadams** [comment]
May also be worth considering a `MethodImplOptions` value for known multimorphic/megamorphic call sites? 

Through perhaps instrumenting Tier0/Tier1 would determine this and could "deoptimze" the callsite automatically; or it the fallback dispatch stub grew beyond a certain number of permutations this could trigger it.

File: src/jit/morph.cpp [hunk 2]
```diff
@@ -6681,6 +6698,13 @@ void Compiler::fgMorphCallInlineHelper(GenTreeCall* call, InlineResult* result)
         return;
     }
 
+    // Re-check this because guareded devirtualization may allow these through.
```
Comment (sebastienros) [inline src/jit/morph.cpp]: Typo: guareded

File: Documentation/design-docs/GuardedDevirtualization.md [hunk 3]
```diff
@@ -0,0 +1,522 @@
+# Guarded Devirtualization
+
+## Overview
+
+Guarded devirtualization is a proposed new optimization for the jit in .Net Core
```
Comment (davkean) [inline Documentation/design-docs/GuardedDevirtualization.md]: Nit: ".NET" over ".Net"

**Comment by AndyAyersMS** [comment]
If you peer back just a bit in the commit chain there is a version where the runtime keeps track of which classes implement a given interface. And if there's just one implementing class for an interface call at the time a method is jitted then the jit will guess that class.

That may in fact be the thing we try to get fully working for 3.0, since it tends to impact a relatively small number of call sites (so less code bloat and jit time cost) and should have a pretty good CQ payoff.

File: Documentation/design-docs/GuardedDevirtualization.md [hunk 4]
```diff
@@ -0,0 +1,533 @@
...
+
+## Overview
+
+Guarded devirtualization is a proposed new optimization for the jit in .NET Core
+3.0. This document describes the motivation, initial design sketch, and highlights
+various issues needing further investigation.
+
+## Motivation
+
+The .NET Core jit is able to do a limited amount of devirtualization for virtual
```
Comment (gfoidl) [inline Documentation/design-docs/GuardedDevirtualization.md]: Nit: "jit" is used here, in other documents "JIT" is used (if I remember correct). So I suppose to always use "JIT" to be consistent within coreclr-repo.

**Comment by gfoidl** [comment]
> what is the best mechanism for guessing which class to test for? 

IMHO "add instrumenting Tier1 to collect data and Tier2 to optimize?" sounds good, as Tier 1 is more "stationary" than Tier 0 (i.e. I mean reflects the actual workload better than the startup-phase).

**Comment by benaadams** [comment]
To quantify, interfaces used in base ASP.NET Core that this could benefit:

aspnetcoreinterfaces

File: Documentation/design-docs/GuardedDevirtualization.md [hunk 5]
```diff
@@ -0,0 +1,533 @@
...
+As with virtual calls you may strongly suspect the two class case for interface
+calls is special. And you'd be right.
+
+If we mix a third class in as we did above, we see similar changes in the
+performance mix for interface calls, as seen below. But also as with virtual calls
+the jit's guess doesn't have to be all that good to see payoffs. At around 10%
+correct, guessing wins on average, and around 30% correct guessing is always a 
+perf win.
+
+![three classes interface devirt](ThreeClassesInterface.JPG)
```
[the remark this answers is not in the document]
Comment (AndyAyersMS) [reply Documentation/design-docs/GuardedDevirtualization.md]: Forgot to add it. Will be there in my next push.

File: Documentation/design-docs/GuardedDevirtualization.md [hunk 6]
```diff
@@ -0,0 +1,533 @@
...
+even guessing the less likely case can pay off and doesn't hurt performance.
+
+One might suspect at this point that the two class case is a special case and that
+the results do not hold up in more complex cases. More on that shortly.
+
+Before moving on, we should point out that virtual calls in the current
+CLR are a bit more expensive than in C++, because the CLR uses a two-level method
+table. That is, the indirect call sequence is something like:
+```asm
+000095 mov      rax, qword ptr [rcx]                 // fetch method table
```
[the remark this answers is not in the document]
Comment (AndyAyersMS) [reply Documentation/design-docs/GuardedDevirtualization.md]: Sure. I'll go with `;` everywhere.

File: Documentation/design-docs/GuardedDevirtualization.md (hunk 3 above)
Comment (AndyAyersMS) [reply Documentation/design-docs/GuardedDevirtualization.md]: Thanks, fixed.

File: src/jit/morph.cpp (hunk 2 above)
Comment (AndyAyersMS) [reply src/jit/morph.cpp]: Thanks. Probably not the only one.

File: Documentation/design-docs/GuardedDevirtualization.md (hunk 1 above)
Comment (AndyAyersMS) [reply Documentation/design-docs/GuardedDevirtualization.md]: Will stick with caps for now, though it looks wrongish.

File: Documentation/design-docs/GuardedDevirtualization.md (hunk 4 above)
Comment (AndyAyersMS) [reply Documentation/design-docs/GuardedDevirtualization.md]: Sure, will update...

**Comment by AndyAyersMS** [comment]
Started looking at the failures. 

Something is going wrong in the void return case (eg method returning struct implicitly by-ref... as in GitHub_20499). We can't map a GT_RET_EXPR to a GT_NOP -- if we fail to inline we then lose the attached call.

**Comment by fiigii** [comment]
> Total bytes of diff: 1923401 (5.15% of base)
    diff is a regression.

- It would be great if we have perf data as well (like TechEmpower).
- We should add a compile flag for this feature.
- Adding deoptimization in tiered JIT may help to optimize code size and the fallback handling (e.g., guard propagation, actually it also helps assertion propagation).

**Comment by benaadams** [comment]
Another common aspnet monomorphic interface callsite (which may be covered) is via generic interface dispatch; with type categorized logging via [`interface ILogger<out TCategoryName> : ILogger`](https://github.com/aspnet/Logging/blob/2d2f31968229eddb57b6ba3d34696ef366a6c71b/src/Microsoft.Extensions.Logging.Abstractions/ILoggerOfT.cs) being the most obvious demonstrator:
```csharp
public class MyPage : PageModel
{
    private readonly ILogger<MyPage> _logger;
    public MyPage(ILogger<MyPage> logger) => _logger = logger;

    public void OnGet() => _logger.LogInformation("Get Request"); // Call site
}
```
Further complicating; it may be the generic interface held in a non-generic field
```csharp
public class MyPage : PageModel
{
    private readonly ILogger _logger;
    public MyPage(ILogger<MyPage> logger) => _logger = logger;

    public void OnGet() => _logger.LogInformation("Get Request"); // Call site
}
```
Further complicating; the fast-path non allocating when logger is off route goes via a static action created by the [`LoggerMessage` helper `Define`s](https://github.com/aspnet/Extensions/blob/c89a5b5a28eda467399cff709464d0ab904b27cd/src/Logging/Logging.Abstractions/src/LoggerMessage.cs#L79-L90); which probably also introduces delegate speculation?:
```csharp
public class MyPage : PageModel
{
    private readonly static Action<ILogger, Exception> _log = 
        LoggerMessage.Define(
            eventId: 1,
            logLevel: LogLevel.Information,
            formatString: "Get Request");

    private readonly ILogger _logger;
    public MyPage(ILogger<MyPage> logger) => _logger = logger;

    public void OnGet() => _log(_logger, null); // Call site
}
```
Some common more complicated use-cases for the mix?

**Comment by benaadams** [comment]
For something that gets executed millions of times per second during the TE benchmarks, this [fairly innocuous line in Kestrel](https://github.com/aspnet/AspNetCore/blob/9e73c3382f4d9e6ba47afff6a1467ace945c77e7/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs#L1074) is probably a wild ride:
```csharp
Log.ConnectionKeepAlive(ConnectionId);
```

**Comment by AndyAyersMS** [comment]
@fiigii will get perf data once things are bit further along... want to fix remaining bugs in the transformation and iron out some annoyances first.

@benaadams thanks much for the examples.

**Comment by AndyAyersMS** [comment]
Hoping this [x64 failure](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_no_tiered_compilation_innerloop_prtest/4227/) is just a glitch:
```
CSC : error CS2011: Error opening response file 
'D:\j\workspace\x64_checked_w---fa31220a\bin\int\Managed\baseservices\typeequivalence\impl\TypeImpl\TypeImpl.rsp' 
[D:\j\workspace\x64_checked_w---fa31220a\tests\src\baseservices\typeequivalence\impl\TypeImpl.csproj]
```

**Comment by fiigii** [comment]
> Hoping this x64 failure is just a glitch:

Yes,  it is also failed in https://github.com/dotnet/coreclr/pull/21264

**Comment by AndyAyersMS** [comment]
@dotnet-bot test Windows_NT x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0)

**Comment by benaadams** [comment]
@dotnet-bot test Windows_NT x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0)

**Comment by benaadams** [comment]
> > Hoping this x64 failure is just a glitch:

> Yes, it is also failed in #21264

Workaround merged https://github.com/dotnet/coreclr/pull/21294 (Switching off test)

**Comment by AndyAyersMS** [comment]
Needed to rebase to pick up recent fixes. The large commit chain in the initial PR had several conflicts and marginal value so decided to squash it all down...

**Comment by AndyAyersMS** [comment]
Here's an example of the poor interaction of guarded devirt and late devirt: both arms of the guarded call devirtualize (one early, one late) and so both end up calling `B.F` (early devirt'd call gets inlined, late one doesn't):

```C#
// example of bad interaction between guarded and late devirt.

class B
{
    public virtual int F() => 33;
}

class D : B
{
    public override int F() => 44;
}

class X
{
    static B G() => new B();

    public static int Main()
    {
        // GuardedDevirt will insert runtime type test here.
        //
        // Then residiual virtual call to F() will devirt "late"
        // after inlining G()
        return G().F() + 100 - 33;
    }
}
```

```asm
; Assembly listing for method X:Main():int
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 OutArgs      [V00    ] (  1,  1   )  lclBlk (32) [rsp+0x00]   "OutgoingArgSpace"
;  V01 tmp1         [V01,T00] (  3,  4.20)     ref  ->  rax         class-hnd exact "spilling ret_expr"
;  V02 tmp2         [V02,T02] (  3,  1.50)     int  ->  rsi         "guarded devirt return temp"
;* V03 tmp3         [V03    ] (  0,  0   )     ref  ->  zero-ref    class-hnd exact "guarded devirt this exact temp"
;  V04 tmp4         [V04,T01] (  2,  4   )     ref  ->  rax         class-hnd exact "NewObj constructor temp"
;
; Lcl frame size = 32

G_M10001_IG01:
       56                   push     rsi
       4883EC20             sub      rsp, 32

G_M10001_IG02:
       48B92813845EFB7F0000 mov      rcx, 0x7FFB5E841328
       E8BCE7885F           call     CORINFO_HELP_NEWSFAST
       48B92813845EFB7F0000 mov      rcx, 0x7FFB5E841328
       483908               cmp      qword ptr [rax], rcx
       7507                 jne      SHORT G_M10001_IG03
       BE21000000           mov      esi, 33
       EB0A                 jmp      SHORT G_M10001_IG04

G_M10001_IG03:
       488BC8               mov      rcx, rax
       E866F4FFFF           call     B:F():int:this
       8BF0                 mov      esi, eax

G_M10001_IG04:
       8D4643               lea      eax, [rsi+67]

G_M10001_IG05:
       4883C420             add      rsp, 32
       5E                   pop      rsi
       C3                   ret

; Total bytes of code 61, prolog size 5 for method X:Main():int
```
We could perhaps fix this up later if the jit knew that the `newobj` helper installed its argument in the vtable slot. But probably better to catch this during late devirt and undo the guarded transform on the spot.

**Comment by AndyAyersMS** [comment]
[OSX build](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_osx10.12_innerloop_flow_prtest/10719/) failed with what look like in-use files:
```
16:56:54 [ 64%] Built target paltest_wcschr_test1
16:56:54 ld: can't write to output file: paltest_wcscmp_test1, errno=28 for architecture x86_64
16:56:54 clang: error: linker command failed with exit code 1 (use -v to see invocation)
16:56:54 make[2]: *** [src/pal/tests/palsuite/c_runtime/wcscmp/test1/paltest_wcscmp_test1] 
```
will retry...

@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by AndyAyersMS** [comment]
[Ubuntu arm64 leg](https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_checked_ubuntu16.04_innerloop_flow_prtest/2422/) has an msbuild failure:
```
12:52:49 
MSBUILD : error MSB4166: Child node "4" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
12:52:49 
12:52:49 Build FAILED.
```
(similar in the other leg).

**Comment by AndyAyersMS** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked Innerloop Build and Test 
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked no_tiered_compilation_innerloop Build and Test

**Comment by AndyAyersMS** [comment]
@dotnet/jit-contrib I think the foundation layer is ready for review.

My plan is to check this in as off by default, then work on heuristics and fixing some of the annoyances like the late/guarded interaction noted above.

@sandreenko can you look at the refactoring of the calli transformer?
@briansull can you look at the other changes... ?

File: src/jit/importer.cpp [hunk 7]
```diff
@@ -19560,14 +19663,22 @@ void Compiler::impMarkInlineCandidate(GenTree*               callNode,
 
     if (call->IsVirtual())
     {
-        inlineResult.NoteFatal(InlineObservation::CALLSITE_IS_NOT_DIRECT);
-        return;
+        if (call->IsGuardedDevirtualizationCandidate())
+        {
+            // Allow guarded devirt calls to be treated as inline candidates.
```
Comment (briansull) [inline src/jit/importer.cpp]: Empty then block...
Could be re-written

File: src/jit/importer.cpp [hunk 8]
```diff
@@ -20091,29 +20271,50 @@ void Compiler::impDevirtualizeCall(GenTreeCall*            call,
     }
 #endif // defined(DEBUG)
 
-    if (!isExact && !objClassIsFinal && !derivedMethodIsFinal)
+    bool canDevirtualize = true;
```
Comment (briansull) [inline src/jit/importer.cpp]: This could also be written as:

`canDevirtualize = isExact || objClassIsFinal || (isInterface && derivedMethodIsFinal);`

File: src/jit/importer.cpp [hunk 9]
```diff
@@ -20446,8 +20662,109 @@ class SpillRetExprHelper
...
+
+//------------------------------------------------------------------------
+// addGuardedDevirtualizationCandidate: potentially mark the call as a guarded
+//    devirtualization candidate
+//
+// Notes:
+//
+// We currently do not mark calls as candidates when prejitting. This was done
+// to simplify bringing up the associated transformation. It is worth revisiting
+// if we think we can come up with good guess classes when prejitting.
```
Comment (briansull) [inline src/jit/importer.cpp]: wording "a good guess for the ... "

File: src/jit/flowgraph.cpp [hunk 10]
```diff
@@ -25557,38 +25576,60 @@ bool Compiler::fgRetargetBranchesToCanonicalCallFinally(BasicBlock*      block,
...
             if (ContainsFatCalli(stmt))
             {
-                StatementTransformer stmtTransformer(compiler, block, stmt);
-                stmtTransformer.Run();
+                FatPointerCallTransformer transformer(compiler, block, stmt);
+                transformer.Run();
+                count++;
+            }
+
+            if (ContainsGuardedDevirtualizationCandidate(stmt))
```
Comment (sandreenko) [inline src/jit/flowgraph.cpp]: In theory could one call be both `fat call` and `guarded devitalization` candidate at the same time?

File: src/jit/flowgraph.cpp [hunk 11]
```diff
@@ -25609,39 +25650,158 @@ class FatCalliTransformer
...
+            thenBlock      = nullptr;
+            elseBlock      = nullptr;
+            origCall       = nullptr;
         }
 
         //------------------------------------------------------------------------
         // Run: transform the statement as described above.
         //
-        void Run()
+        virtual void Run()
```
Comment (sandreenko) [inline src/jit/flowgraph.cpp]: As I see both `FatCalliTransformer` and `GuardedDevirtualizationTransformer ` have their own implementations of `Run` and other functions, who does use this implementation then?

File: src/jit/flowgraph.cpp [hunk 12]
```diff
@@ -25557,38 +25576,60 @@ bool Compiler::fgRetargetBranchesToCanonicalCallFinally(BasicBlock*      block,
 //     subsequent statements
 //   }
 //
-class FatCalliTransformer
+class IndirectCallTransformer
```
Comment (sandreenko) [inline src/jit/flowgraph.cpp]: Maybe it is time to move these helper classes out of this file. It is 25.000 lines long.

File: src/jit/flowgraph.cpp [hunk 13]
```diff
@@ -21871,7 +21886,8 @@ void Compiler::fgInline()
             expr = stmt->gtStmtExpr;
 
             // See if we can expand the inline candidate
-            if ((expr->gtOper == GT_CALL) && ((expr->gtFlags & GTF_CALL_INLINE_CANDIDATE) != 0))
+            if (expr->IsCall() && (((expr->gtFlags & GTF_CALL_INLINE_CANDIDATE) != 0) ||
```
Comment (sandreenko) [inline src/jit/flowgraph.cpp]: I think it will be more readable as
```
if (expr->IsCall())
{
	 GenTreeCall* call = expr->AsCall();
	 if (expr->IsGuardedDevirtualizationCandidate() || call.IsGuardedDevirtualizationCandidate())
```

File: src/jit/importer.cpp [hunk 14]
```diff
@@ -18521,22 +18539,42 @@ void Compiler::impCheckCanInline(GenTree*               call,
                    (varTypeIsStruct(fncRetType) && (fncRealRetType == TYP_STRUCT)));
 #endif
 
+            // Allocate an InlineCandidateInfo structure,
             //
-            // Allocate an InlineCandidateInfo structure
+            // Or, reuse the existing GuardedDevirtualizationCandidateInfo,
+            // which was pre-allocated to have extra room.
```
[the remark this answers is not in the document]
Comment (AndyAyersMS) [reply src/jit/importer.cpp]: They're not really different. At one point they were completely different and then I made the inline part an add-on to the guarded part.

I considered renaming the whole thing but thought leaving them as logically distinct types made things clearer. But perhaps not.

File: src/jit/flowgraph.cpp (hunk 10 above)
Comment (AndyAyersMS) [reply src/jit/flowgraph.cpp]: I suppose maybe one day, if we ever try and guess at indirect call targets?

But currently we don't do this.

File: src/jit/flowgraph.cpp (hunk 13 above)
Comment (AndyAyersMS) [reply src/jit/flowgraph.cpp]: Sure, will update.

File: src/jit/gentree.cpp [hunk 15]
```diff
@@ -9336,7 +9337,20 @@ void Compiler::gtDispNode(GenTree* tree, IndentStack* indentStack, __in __in_z _
             case GT_CALL:
                 if (tree->gtFlags & GTF_CALL_INLINE_CANDIDATE)
                 {
-                    printf("I");
+                    if (tree->gtCall.gtCallMoreFlags & GTF_CALL_M_GUARDED_DEVIRT)
```
Comment (mikedn) [inline src/jit/gentree.cpp]: Isn't this just `IsGuardedDevirtualizationCandidate()`?

File: src/jit/flowgraph.cpp (hunk 11 above)
Comment (mikedn) [reply src/jit/flowgraph.cpp]: Heh, devirtualization implementation uses virtual calls. I hope the native compiler knows how to do devirtualization :grin:

File: src/jit/gentree.cpp (hunk 15 above)
Comment (AndyAyersMS) [reply src/jit/gentree.cpp]: Yes, if I had a `GenTreeCall`

File: src/jit/flowgraph.cpp (hunk 12 above)
Comment (AndyAyersMS) [reply src/jit/flowgraph.cpp]: Agree, but this sort of thing should be done on its own and not as part of a refactoring that potentially modifies behavior.

File: src/jit/flowgraph.cpp (hunk 11 above)
Comment (AndyAyersMS) [reply src/jit/flowgraph.cpp]: I suppose I could make those derived classes `final`, that should do the trick.

File: src/jit/gentree.cpp (hunk 15 above)
Comment (mikedn) [reply src/jit/gentree.cpp]: Am I missing something? You do have `tree->gtCall`

Comment (AndyAyersMS) [reply src/jit/gentree.cpp]: Good point.

**Comment by AndyAyersMS** [comment]
Verified latest is no-diff if I disable Guarded Devirt. With GuardedDevirt enabled we still see the ~5% size increase.

Am going to push a final commit -- once testing above goes green -- that flips the default to disabled, and that's what I will check in.

**Comment by BruceForstall** [comment]
Please remove the "WIP" tag.

**Comment by AndyAyersMS** [comment]
[arm cross checked](https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_windows_nt_innerloop_flow_prtest/2766/) network hangup (same for arm64 cross checked)
```
Will be doing one more push so will let that trigger a retest.
16:15:28     Finished:    JIT.Directed.XUnitWrapper
16:15:36     Finished:    JIT.Performance.XUnitWrapper
16:16:59 FATAL: command execution failed
16:16:59 java.nio.channels.ClosedChannelException
```

**Comment by AndyAyersMS** [comment]
[Perf test runs](https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x86_full_opt_ryujit_smoketest_prtest/7511/) seem perhaps to be looking for python 3.7 and failing to find it:
```
17:59:52 D:\j\w\perf_perflab_---6af0d14a>C:\python3.7.0\python.exe "D:\j\w\perf_perflab_---6af0d14a\Microsoft.BenchView.JSONFormat\tools\submission-metadata.py" --name "coreclr private Guarded devirtualization foundations" --user-email "dotnet-bot@microsoft.com" 
17:59:52 The system cannot find the path specified
```

**Comment by AndyAyersMS** [comment]
@adiaaida does this python 3.7 thing seem familiar?

**Comment by adiaaida** [comment]
@AndyAyersMS yes. We moved the python3.7 artifact to the regular helix queues, so I moved the smoketests jobs to use the regular queue, but we broke dumpling because python3 was the first on the path, so they went back to a previous deployment so the queue lost python3.7. We are working on a new deployment. See https://github.com/dotnet/core-eng/issues/4753

File: src/jit/gentree.h [hunk 16]
```diff
@@ -3774,8 +3801,9 @@ struct GenTreeCall final : public GenTree
         // only used for CALLI unmanaged calls (CT_INDIRECT)
         GenTree* gtCallCookie;
         // gtInlineCandidateInfo is only used when inlining methods
-        InlineCandidateInfo*   gtInlineCandidateInfo;
-        void*                  gtStubCallStubAddr;              // GTF_CALL_VIRT_STUB - these are never inlined
+        InlineCandidateInfo*                  gtInlineCandidateInfo;
+        GuardedDevirtualizationCandidateInfo* gtGuardedDevirtualizationCandidateInfo;
```
Comment (fiigii) [inline src/jit/gentree.h]: We probably need to handle the new field in `Compiler::gtCloneExpr`. If not, we would see JITStress failures.

Comment (AndyAyersMS) [reply src/jit/gentree.h]: Thanks for pointing this out. Unfortunately we can't safely clone inline candidates in isolation like this, as they and the associated `GT_RET_EXPR`s must refer to one another. Also we can't safely share inline candidate info across multiple calls.

To put it another there are some special and unusual rules in the IR early on and any cloning of an inline candidate requires cloning of the `GT_RET_EXPR` and special post processing to fix things up (which is a good part of what the guarded devirt transformation and up-front `GT_RET_EXPR` spilling does).

So what goes on here when cloning calls is wrongish but can't easily be made right. We should I suppose null out the candidate information as that would be somewhat less wrong, but it is still wrong. And we need to clone calls so banishing cloning for inline candidates or guarded devirtualization candidates outright (like we do for `GT_RET_EXPR`s) doesn't help either.

I doubt stress mode cloning runs before we've inlined as it would already be busted (and after we get past `fgInline`  these special  complications vanish). So I further doubt these changes will pose any new problems beyond the ones we already have and are avoiding.

But I could be wrong. I'll keep an eye on cloning as I continue working on this feature, but for now don't expect to need to change this aspect.

Comment (AndyAyersMS) [reply src/jit/gentree.h]: Thinking about this a bit more, probably the right change is to ban cloning of inline candidates via `gtCloneExpr` and introduce a separate method that can be used to clone them.

Because inline candidate calls can't ever be subtrees or live on the eval stack it's unlikely anyone would clone them inadvertently (say as part of cloning some ancestor tree), so having a deliberate API to call in this case seems like it might be a good compromise.

Will follow up on this in a subsequent change.

**Comment by AndyAyersMS** [comment]
Perf tests like those in the design doc: dotnet/performance#174
