### PR TITLE
Compute sizeof array instead of pointer

### PR DESCRIPTION
**Pull request by am11**
gcc8 and clang8-pre has implemented `Wsizeof-pointer-div` analysis, which identifies two issues on amd64.

### CODE REVIEW

**Comment by am11** [comment]
@jkotas, I had builds and tests running with different versions of these compilers and here are the logs captured:

gcc8:

> /dev/s/g/coreclr/src/inc/utilcode.h:157:32: error: division ‘sizeof (\_\_wchar_16_cpp__* {aka char16_t*}) / sizeof (\_\_wchar_16_cpp__ {aka char16_t})’ does not compute the number of array elements [-Werror=sizeof-pointer-div]
> ...
> /dev/s/g/coreclr/src/vm/frames.h:3615:45: error: division ‘sizeof (OBJECTREF*) / sizeof (OBJECTREF)’ does not compute the number of array elements [-Werror=sizeof-pointer-div]

clang8 (beta):

> /dev/s/g/coreclr/src/inc/utilcode.h:157:32: error: 'sizeof (buff)' will return the size of the pointer, not the array itself [-Werror,-Wsizeof-pointer-div]
> ...
> /dev/s/g/coreclr/src/vm/frames.h:3615:45: error: 'sizeof (pStaticSlots)' will return the size of the pointer, not the array itself [-Werror,-Wsizeof-pointer-div]

File: src/vm/methodtable.cpp [hunk 1]
```diff
@@ -3226,7 +3226,7 @@ void MethodTable::AllocateRegularStaticBoxes()
     if (pClassCtorInfoEntry != NULL)
     {
         OBJECTREF* pStaticSlots = (OBJECTREF*)(pStaticBase + pClassCtorInfoEntry->firstBoxedStaticOffset);
-        GCPROTECT_BEGININTERIOR(pStaticSlots);
+        GCPROTECT_BEGININTERIOR(*pStaticSlots);
```
Comment (jkotas) [inline src/vm/methodtable.cpp]: This is bad change. Discussed in https://github.com/dotnet/coreclr/issues/23842

File: src/vm/debughelp.cpp [hunk 2]
```diff
@@ -476,7 +476,7 @@ int dumpStack(BYTE* topOfStack, unsigned len)
 
         if (isRetAddr((TADDR)*ptr, &whereCalled))
         {
-            if (_snwprintf_s(buffPtr, buff+NumItems(buff)-buffPtr-1, _TRUNCATE,  W("STK[%08X] = %08X "), (size_t)ptr, *ptr)  <0)
+            if (_snwprintf_s(buffPtr, buff + wcslen(buff) - buffPtr - 1, _TRUNCATE,  W("STK[%08X] = %08X "), (size_t)ptr, *ptr)  <0)
```
Comment (jkotas) [inline src/vm/debughelp.cpp]: This should `nLen`, not `wcslen`.

File: src/vm/methodtable.cpp (hunk 1 above)
Comment (jkotas) [reply src/vm/methodtable.cpp]: Is there a way to tweak the code to make the analysis stop complaining about it?

Comment (am11) [reply src/vm/methodtable.cpp]: Ah, didn't noticed the discussion. Should we suppress `-Wsizeof-pointer-div` in CMakeLists?

Comment (am11) [reply src/vm/methodtable.cpp]: The other way is to inline the suppression: `#pragma clang diagnostic ignored "-Wsizeof-pointer-div"` (and the other one for gcc).

Comment (jkotas) [reply src/vm/methodtable.cpp]: It would be best to tweak the code to make the warning go away, e.g. add extra cast or something similar. What is the exact pattern that the analysis looks for?

Comment (am11) [reply src/vm/methodtable.cpp]: It was looking for the exact `sizeof(x)/sizeof(x[0])` vulgar fraction pattern in both clang v8 and gcc v8. I have extracted the numerator variable in a separate variable and confirmed that it recompiles with both. Thanks!

File: src/vm/debughelp.cpp [hunk 3]
```diff
@@ -476,7 +476,7 @@ int dumpStack(BYTE* topOfStack, unsigned len)
 
         if (isRetAddr((TADDR)*ptr, &whereCalled))
         {
-            if (_snwprintf_s(buffPtr, buff+NumItems(buff)-buffPtr-1, _TRUNCATE,  W("STK[%08X] = %08X "), (size_t)ptr, *ptr)  <0)
+            if (_snwprintf_s(buffPtr, buff + nLen - buffPtr - 1, _TRUNCATE,  W("STK[%08X] = %08X "), (size_t)ptr, *ptr)  <0)
```
Comment (jkotas) [inline src/vm/debughelp.cpp]: `- 1` should not be needed. The method takes the actual buffer size.

Also, could you please fix all places that take buffer size in this method to use the same expression while you are on it? It is a mix right now:

` wcsncpy_s(buffPtr, nLen - (buffPtr - buff)`
_snwprintf_s(buffPtr, buff+ nLen -buffPtr-1,`
`if( formatMethodTable(pMT, buffPtr, static_cast<DWORD>(buff+ nLen -buffPtr-1)) == NULL)`

Maybe add `buffEnd` variable and change all these to be just `buffEnd - buff`.
