### PR TITLE
Freebsd sysctl

### PR DESCRIPTION
**Pull request by wfurt**
clone of #27817, correct branch this time ;(

This is regression caused by #27048 and build fails like:
```
[ 28%] Built target utilcodestaticnohost
/home/furt/git/coreclr/src/pal/src/misc/sysinfo.cpp:382:10: error: use of undeclared identifier 'sysctlnametomib'
    rc = sysctlnametomib("vm.swap_info", mib, &length);
         ^
[ 35%] Built target cee_dac
/home/furt/git/coreclr/src/pal/src/misc/sysinfo.cpp:390:18: error: use of undeclared identifier 'sysctl'
            rc = sysctl(mib, 3, &xsw, &length, NULL, 0);
                 ^
/home/furt/git/coreclr/src/pal/src/misc/sysinfo.cpp:599:30: error: use of undeclared identifier 'sysctlbyname'
        const bool success = sysctlbyname("hw.l3cachesize", &cacheSizeFromSysctl, &sz, nullptr, 0) == 0
                             ^
/home/furt/git/coreclr/src/pal/src/misc/sysinfo.cpp:600:16: error: use of undeclared identifier 'sysctlbyname'
            || sysctlbyname("hw.l2cachesize", &cacheSizeFromSysctl, &sz, nullptr, 0) == 0
               ^
/home/furt/git/coreclr/src/pal/src/misc/sysinfo.cpp:601:16: error: use of undeclared identifier 'sysctlbyname'
            || sysctlbyname("hw.l1dcachesize", &cacheSizeFromSysctl, &sz, nullptr, 0) == 0;
[ 35%] Generating eventpipe/eventpipehelpers.cpp, eventpipe/dotnetruntime.cpp, eventpipe/dotnetruntimerundown.cpp, eventpipe/dotnetruntimestress.cpp, eventpipe/dotnetruntimeprivate.cpp

```

The problem is that FreeBSD has HAVE_SYSCONF and that seems mutually elusive in includes but later on used with different guard.  Maybe it would be better to set HAVE_SYSCONF=0 on Linux if we want to avoid usage of it.

This is minimal change to fix compilation while preserving spirit of #27048.
Note that FreeBSD does not have vm.swap_info. We will probably need separate effort to find some equivalent. 

cc: @omajid

### CODE REVIEW

File: src/pal/src/misc/sysinfo.cpp [hunk 1]
```diff
@@ -31,9 +31,12 @@ Revision History:
 
 #if HAVE_SYSCONF
 // <unistd.h> already included above
-#elif HAVE_SYSCTL
+#endif
+#if HAVE_SYSCTL && !defined(__linux__)
```
Comment (lpereira) [inline src/pal/src/misc/sysinfo.cpp]: Ideally I'd like to see the change in the build system.  A quick grepping also found instances of `HAVE_SYSCTL` in GC too.

Comment (wfurt) [reply src/pal/src/misc/sysinfo.cpp]: Reason why the other work is that it is guarded by HAVE_SYSCTLBYNAME and that one does not exit on Linux so it did not get included in  #27048 and it works as expected on BSD and OSX. Using it here also works if that is better than adding extra linux check. 

Should we set HAVE_SYSCTL=0 on Linux @omajid? 
Even if glibc deprecates it, musl libc may not but I'm not sure if we have any Linux functionality depending on it. From the search it seems like we use sysconf for all we need on Linux. 

BTW hw.l3cachesize works on OSX but FreeBSD does not have it. So the code would compile  but we would end up with cacheSize = 0;

Comment (am11) [reply src/pal/src/misc/sysinfo.cpp]: From: https://github.com/dotnet/coreclr/pull/27827

>>  I'm wondering if we should also guard rest of the code with HAVE_SYSCTLBYNAME instead of HAVE_SYSCTL so they are in balance.
>
> I think it makes sense as in this context, `HAVE_SYSCTLBYNAME` is more reliable macro to determine whether sys/sysctl.h should be included. It is also used in another file where `sysctlnametomib` is used.

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in #27549 the dotnet/runtime repository will be used going forward for changes to this code base. Closing this PR as no more changes will be accepted into master for this repository. If you’d like to continue working on this change please move it to dotnet/runtime.
